### ISSUE TITLE
Missing data from `miner_fee_debt` at epoch `1957803`

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#1017]
### Describe the bug:

Expecting data from SP `f07830` when running task `miner_fee_debt` at epoch `1957803`. When running this task focused on this epoch, the output does not include this miner's record.

We can confirm the extractor is executing where lily detects the state diff for this SP.

We expect data at this height for this SP due to data presence from Lily v0.10.1 in production.

### Steps to Reproduce:

1. Run lily v0.11.0 w state that includes epoch `1957803`.
2. Execute `lily job run --tasks="miner_fee_debt" --storage="File1" index height --height=1957803` with storage configured for writing CSVs:

```
        [Storage.File.File1]
          Format = "CSV"
          Path = "/var/lib/lily/"
          OmitHeader = false
          FilePattern = "{table}.csv"
```
3. Observe missing records with `cat /var/lib/lily/miner_fee_debt.csv | grep f07830`.

**Comment by frrist** [comment]
closed via https://github.com/filecoin-project/lily/pull/1018
