### ISSUE TITLE
Fault/recover event still happen after a termination event

### ISSUE THREAD

**Issue by xuyaoshell** [filecoin-project/lily#1031]
### Describe the bug:
![image](https://user-images.githubusercontent.com/36436803/184054169-4c816b81-719e-4f6b-9ce3-621267406cb9.png)
Some sectors seem to fault/recover even after a termination event.

**Comment by frrist** [comment]
Thanks for filing @xuyaoshell. A fix has been created int https://github.com/filecoin-project/lily/pull/1032
