### ISSUE TITLE
When the task height is 1960322, there is an error out of memory allocating heap arena metadata

### ISSUE THREAD

**Issue by LINJINTIANDE** [filecoin-project/lily#1063]
### Describe the bug:
This problem occurs when walk or fill to 1960322 height, the task is actor, or miner series tasks.
Computer Configuration:
1. CPU Authentic AMD7302
2. Memory 1t
3. GPU2080
### Steps to Reproduce:
Running a walk job like this:

` lily job run  --storage=lily --tasks=actor,actor_state --storage=lily walk  --from=1960322 --to=1960322
`

**Comment by placer14** [comment]
I guess you've tested it with both v0.11 and v0.12? What are you using to manage the lily daemon process? 

Lily doesn't directly manage the memory consumption and will attempt to grow into whatever memory resources are available to it. This might explain the OOM and it might not be specific to that height in particular but that height might have an explosion of state which triggers it for you?

What are you using the manage the Lily daemon process? Are you doing anything to manage the memory resources directly or are you letting the the OS handle resources directly for that process? If so, I would recommend systemd or some containerized platform which allows you to tune the available resources for that process.

If that's a heavy lift, there are a few ENVVARs which you can use the manage the memory consumption of Lily. [Here's my description written in a thread to another individual about the same found in the Filecoin slack.](https://filecoinproject.slack.com/archives/C0174P5M11T/p1659975845217449?thread_ts=1659863701.714039&cid=C0174P5M11T)

> We have a distributed deployment configuration now and this doesn't apply to that style of deployment. As a single daemonized instance, you would want to have that instance, for example, take all miner* prefixed tasks and have them on the same instance. Let me know if you'd like me to elaborate further on this.

> Some things to consider around resource alloc:
> - Each independent job will load two statetrees into memory from disk to extract changes on-chain. Those states (as subtrees) are left cached in memory. So memory usage will balloon to the soft memory limits imposed by the environment. You can directly influence the cache size with LILY_STATESTORE_CACHE_SIZE and LILY_BLOCKSTORE_CACHE_SIZE.

> - Disk usage varies greatly depending on the size of the repo and is multiplied by the number of parallel jobs (including staying in sync, if applicable). The store write-locks so staying in sync is expensive if other tasks are expected to run as well. This is the main problem that the distributed deployment solves. It allows a node to only accept new work once it has that state locally available rather than blocking with sync between each task-height task.

> - The estimate is a generous datapoint for consideration and not prescriptive. Will definitely share more of the data once I have experimented more.

**Comment by LINJINTIANDE** [comment]
🙏! I really did not limit memory through containerization, but let the system manage memory directly, thank you for your suggestion!

**Comment by LINJINTIANDE** [comment]
🙏! I really did not limit memory through containerization, but let the system manage memory directly, thank you for your suggestion!

**Comment by placer14** [comment]
I'm going to close this as a non-issue, though please report back if you continue to have issues. 🤝

**Comment by LINJINTIANDE** [comment]
I set these two parameters
LILY_BLOCKSTORE_CACHE_SIZE=500000, LILY_STATESTORE_CACHE_SIZE=300000
But when running to this 1960322, there will be an error: out of memory allocating heap arena metadata, I don't think this problem occurs because I don't have enough memory. The cpu with 32 cores at this height skyrocketed to 100%, and then dropped sharply to a lower value. , and then the program crashes. (This will not happen at other altitudes) I implore and hope that you run the task of altitude 1960322 to see if the same problem occurs
![image](https://user-images.githubusercontent.com/42436479/191156421-f86f79b6-579e-4ee9-93d0-1d4bb30bf87d.png)

**Comment by LINJINTIANDE** [comment]
**This is the case of the entire error log**
https://drive.google.com/file/d/1Ts8cwCxhdCM6z8jw_MXwAWHRD37ub6R4/view?usp=sharing
**When I comment the code about monitoring, the task can run normally**
project/lily/blob/d451f36e8d43f8c2d14474aae2bca8598693c0df/tasks/actorstate/raw/actor.go#L24

**Comment by birdychang** [comment]
should be fixed in https://github.com/filecoin-project/lily/issues/1191
