### ISSUE TITLE
Define and implement MinerBeneficiary schema and extraction

### ISSUE THREAD

**Issue by frrist** [filecoin-project/lily#1077]
### Description
In v9 actors, the MinerInfo structure received [three new field](https://github.com/filecoin-project/go-state-types/blob/master/builtin/v9/miner/miner_state.go#L125-L134)s:
```go
// Beneficiary address for this miner.
// This is the address that tokens will be withdrawn to
Beneficiary addr.Address

// Beneficiary's withdrawal quota, how much of the quota has been withdrawn,
// and when the Beneficiary expires.
BeneficiaryTerm BeneficiaryTerm

// A proposed change to `BenificiaryTerm`
PendingBeneficiaryTerm *PendingBeneficiaryChange
```

I propose a new schema/model `MinerBeneficiaryInfo` be created to track this data:
```sql
CREATE TABLE miner_beneficiary_info (
  height bigint NOT NULL,
  state_root text NOT NULL,
  miner_id text NOT NULL,
  
  -- the address
  beneficiary text NOT NULL,
  
  -- term info
  quota numeric NOT NULL,
  used_quota numeric NOT NULL,
  expiration bigint NOT NULL,
  
  -- pending term changes (nullable as they are not required)
  new_beneficiary text,
  new_quota numeric,
  new_expiration bigint
  approved_by_beneficiary boolean,
  approved_by_nominee boolean
);
```

This table will update iff:
1. the beneficiary's address changes
2. any of term info or pending term changes feilds's change

**Comment by placer14** [comment]
Looks good!

Some recommended indices:

- `height (ASC),state_root,miner_id` btree
- `height DESC` btree
- `beneficiary` hash

I considered an index for the `new_beneficiary` column, but I suspect that won't be as useful generally. Maybe I'm wrong?
