### ISSUE TITLE
Height 2398025 task multisig_approvals error

### ISSUE THREAD

**Issue by LINJINTIANDE** [filecoin-project/lily#1100]
### Describe the bug:
height 2398025 task multisig_approvals reported the following error ：[{"Addr": "f01936908", "Error": "failed to find transaction for message bafy2bzaced4y5yywdpf6btwygylamqurv2hjwo4l6mzfqbrevumso6cho37sq: pending transaction 7 not found"}] 

### Steps to Reproduce:
lily job run  --storage=lily --tasks=multisig_approvals  walk  --from=2398025  --to=2398025

**Comment by davidgasquez** [comment]
Hey there! Adding that we're hitting the same issue in our pipelines.

**Comment by kasteph** [comment]
Confirming that it exists on filfox: https://filfox.info/en/message/bafy2bzaced4y5yywdpf6btwygylamqurv2hjwo4l6mzfqbrevumso6cho37sq

**Comment by frrist** [comment]
We can depreciate this task in favor of view derived from the vm_messages table:
```sql
select vm.height as height, vm.state_root as state_root, vm.source as message, vm."from" as multisig_id, pm."from" as approver, m.method as method, pm.method as method_name, pm.params->>'To' as to, pm.params->'Value'->>'Int' as value, r.gas_used
from visor.vm_messages vm
         left join visor.parsed_messages pm on pm.cid = vm.source
left join visor.messages m on m.cid = vm.source
left join visor.receipts r on r.message = vm.source
where vm.actor_code = 'bafk2bzacec4va3nmugyqjqrs3lqyr2ij67jhjia5frvx7omnh2isha6abxzya' -- multisig_v8 actor code.
```
