### ISSUE TITLE
id-address task to get the problem of height higher than the chain height

### ISSUE THREAD

**Issue by Huang-Xinzhong** [filecoin-project/lily#1118]
For example, the corresponding height in the f02011956 table is 2510246, but the height of the first message of this ID is 2510245, is this bug, why is it designed like this

**Comment by frrist** [comment]
The message appears on the chain at height `2510245`, but it is not executed until height `2510246`. Only once the message is executed does the actor it was sent to get created in the state tree. Therefore this behavior is expected under the rules of expected [Expected Consensus](https://spec.filecoin.io/algorithms/expected_consensus/)
