### ISSUE TITLE
capture orphan blocks

### ISSUE THREAD

**Issue by kasteph** [filecoin-project/lily#1176]
### Description

We need to also capture orphan blocks to monitor chain health.

### Acceptance criteria

Modify the block_parents tasks s.t. it also includes orphan blocks like in https://filscan.io/cw

### Where to begin

-  [block parents task](https://github.com/filecoin-project/lily/blob/fe4a939fe623f8e4b3424adc2fae91554b149121/tasks/blocks/parents/task.go#L40)

**Comment by jennijuju** [comment]
Hi. - I would like for. this to move forward for longer term monitoring purpose. IIRC we hit some blockers, what was it?

**Comment by Terryhung** [comment]
Hi @jennijuju,

We had implemented the function for monitoring the orphan blocks: https://github.com/filecoin-project/lily/pull/1265.
