### ISSUE TITLE
do we have to upgrade lily to v0.15.0 before the 27th? 

### ISSUE THREAD

**Issue by wuqinqiang** [filecoin-project/lily#1182]
The main network is going to be strongly updated to lotusv1.22.0 on the 27th,I don't see any version of lily about lotusv1.22.0,do we have to upgrade lily to v0.15.0 before the 27th?

**Comment by wuqinqiang** [comment]
> The main network is going to be strongly updated to lotusv1.22.0 on the 27th,I don't see any version of lily about lotusv1.22.0,do we have to upgrade lily to v0.15.0 before the 27th?

@Terryhung

**Comment by birdychang** [comment]
@wuqinqiang yes, please upgrade lily to [v.0.15.1](https://github.com/filecoin-project/lily/releases/tag/v0.15.1) before 27th.
