### ISSUE TITLE
Support lotus chain prune command

### ISSUE THREAD

**Issue by birdychang** [filecoin-project/lily#1187]
### Description
Lily should add the lotus chain prune command:
https://lotus.filecoin.io/lotus/configure/splitstore/#manual-chain-store-garbage-collection

### Acceptance criteria
`lily chain prune` would proxy to the lotus implementation.

### Where to begin
https://github.com/filecoin-project/lily/blob/master/commands/chain.go
https://lotus.filecoin.io/lotus/configure/splitstore/#manual-chain-store-garbage-collection

**Comment by kasteph** [comment]
closed by #1198
