### ISSUE TITLE
chain sync bug

### ISSUE THREAD

**Issue by wuqinqiang** [filecoin-project/lily#1189]
### Describe the bug:

I saw that the sync is more than a thousand heights behind and I saw a lot of error logs like this

023-04-27T22:11:17.332Z        WARN    chain   chain/sync.go:218       InformNewHead called on block marked as bad: bafy2bzacedxzhhyzu5tpqwu7n4t2prqslaszx5on77l4li3jsz52gowfksqzy (reason: linked to bafy2bzacedtuxktmc45niyrrv4526ya6g6i42vgyjoxe2n2sebeyiiraicwya caused by: [bafy2bzaceak7hkrjgv2wybvkoqzvulbfiq4emlakopda6cvwy3j27ofajrfg4] 2 errors occurred:
        * block had invalid messages:
    [github.com/filecoin-project/lotus/chain/consensus.CommonBlkChecks.func1](http://github.com/filecoin-project/lotus/chain/consensus.CommonBlkChecks.func1)
        /root/go/pkg/mod/[github.com/filecoin-project/lotus@v1.23.0/chain/consensus/common.go:83](http://github.com/filecoin-project/lotus@v1.23.0/chain/consensus/common.go:83)
  - failed to compute tipsettate for {bafy2bzacedjju3gvj3cvb37nan3ozddta666d5akskjfvivtfcoca5244iqsw,bafy2bzacecdndor6ose5hur5ublip3mhkzal5dihnk2vgog4tcct36lsmcmt2}:
    [github.com/filecoin-project/lotus/chain/consensus.checkBlockMessages](http://github.com/filecoin-project/lotus/chain/consensus.checkBlockMessages)
        /root/go/pkg/mod/[github.com/filecoin-project/lotus@v1.23.0/chain/consensus/common.go:192](http://github.com/filecoin-project/lotus@v1.23.0/chain/consensus/common.go:192)
  - making vm:
    [github.com/filecoin-project/lotus/chain/consensus.(*TipSetExecutor).ApplyBlocks](http://github.com/filecoin-project/lotus/chain/consensus.(*TipSetExecutor).ApplyBlocks)
        /root/go/pkg/mod/[github.com/filecoin-project/lotus@v1.23.0/chain/consensus/compute_state.go:197](http://github.com/filecoin-project/lotus@v1.23.0/chain/consensus/compute_state.go:197)
  - failed to create FVM:
    [github.com/filecoin-project/lotus/chain/vm.NewFVM](http://github.com/filecoin-project/lotus/chain/vm.NewFVM)
        /root/go/pkg/mod/[github.com/filecoin-project/lotus@v1.23.0/chain/vm/fvm.go:287](http://github.com/filecoin-project/lotus@v1.23.0/chain/vm/fvm.go:287)
  - failed to create memory pool mapping

Caused by:
    0: mmap failed to allocate 0x709ca0000000 bytes
    1: Cannot allocate memory (os error 12)
        * get tipsetstate(2809803, [bafy2bzacedjju3gvj3cvb37nan3ozddta666d5akskjfvivtfcoca5244iqsw bafy2bzacecdndor6ose5hur5ublip3mhkzal5dihnk2vgog4tcct36lsmcmt2]) failed:
    [github.com/filecoin-project/lotus/chain/consensus.CommonBlkChecks.func3](http://github.com/filecoin-project/lotus/chain/consensus.CommonBlkChecks.func3)
        /root/go/pkg/mod/[github.com/filecoin-project/lotus@v1.23.0/chain/consensus/common.go:103](http://github.com/filecoin-project/lotus@v1.23.0/chain/consensus/common.go:103)
  - making vm:
    [github.com/filecoin-project/lotus/chain/consensus.(*TipSetExecutor).ApplyBlocks](http://github.com/filecoin-project/lotus/chain/consensus.(*TipSetExecutor).ApplyBlocks)
        /root/go/pkg/mod/[github.com/filecoin-project/lotus@v1.23.0/chain/consensus/compute_state.go:197](http://github.com/filecoin-project/lotus@v1.23.0/chain/consensus/compute_state.go:197)
  - failed to create FVM:
    [github.com/filecoin-project/lotus/chain/vm.NewFVM](http://github.com/filecoin-project/lotus/chain/vm.NewFVM)
        /root/go/pkg/mod/[github.com/filecoin-project/lotus@v1.23.0/chain/vm/fvm.go:287](http://github.com/filecoin-project/lotus@v1.23.0/chain/vm/fvm.go:287)
  - failed to create memory pool mapping

Caused by:
    0: mmap failed to allocate 0x709ca0000000 bytes
    1: Cannot allocate memory (os error 12)

)

**Comment by birdychang** [comment]
https://filecoinproject.slack.com/archives/CPFTWMY7N/p1682600719322499

**Comment by wuqinqiang** [comment]
I can't understand why you have to be in slack to know what's going on.

**Comment by birdychang** [comment]
I don’t have a solution.Iit’s coming from lotus and there are people facing similar issues discussing in the official lotus help slack channel.

**Comment by birdychang** [comment]
I think your best bet is to re-import the node. Also, please specify EnableSplitstore in config.toml since it’s a required configuration now.

**Comment by LINJINTIANDE** [comment]
1: lotus chain sethead bafy2bzacebyid4tknxy7euy76tmswnxjppngdl2mnpmqqa5kbsbr45dr4r43y (switch height to before upgrade)
2: Check if your version is lily v1.15.1
3: If it still doesn’t work, first switch to lotus 22.1, version 23 and then switch to lily after synchronization

Because I also encountered this problem last night

**Comment by birdychang** [comment]
> `EnableSplitstore` is disabled and I ran it for a day without any issues.
> 
> Previously, when running the Lily program, every one to two weeks, Lily would occasionally fall significantly behind and fail to keep up with the latest height. This would cause tasks assigned to these machines to fail. I had to restart Lily in order for it to return back to normal. I suspect that this was caused by EnableSplitstore=true, so I configured this value as false. Have you encountered similar problems?

Badger data store performance degrades as data grows. We have to periodically reset data store and start from a recent snapshot. We used to turn off split store but we are trying it out after this release. You can try turning off hot store full gc that might cause the node to fall behind.
```
[Chainstore]
  EnableSplitstore = true
  [Chainstore.Splitstore]
    ColdStoreType = "discard"
    HotStoreFullGCFrequency = 0
    HotStoreMaxSpaceTarget = 0
```

**Comment by Shekelme** [comment]
On my quasi-archival node the splitstore is disabled, and I faced the same issue.
lotus version 1.25.2+mainnet+git.f51f83bfe
```
{"level":"warn","ts":"2024-02-04T20:34:35.387+0300","logger":"chain","caller":"chain/sync.go:218","msg":"InformNewHead called on block marked as bad: bafy2bzacedukrpxz37go2m5daanq7ewt5o7vlpnsqwymh6a3wk4dk6g5gunws (reason: linked to bafy2bzacebiyxbrli763o6zk7wntt5obvi5qih4jbku2iht5hkpkeonvxqgfk caused by: [bafy2bzaceactbza4qcnersz5fld7gt2azimlnftnezqug5obfkhtkilqrweio] 1 error occurred:\n\t* parent state root did not match computed state (bafy2bzacecwnbvlmn2vlnlpfeoqmrc2kkwwjq4cwvrqcog2utbizt4ozpmkny != bafy2bzacecndd4ioo3mhgi4wizs7hl62crugebkye3cvp7ikqvzxcplfmudku):\n    github.com/filecoin-project/lotus/chain/consensus.CommonBlkChecks.func3\n        /home/admfc/lotus/chain/consensus/common.go:118\n\n)"}
{"level":"warn","ts":"2024-02-04T20:34:35.983+0300","logger":"chain","caller":"chain/sync.go:218","msg":"InformNewHead called on block marked as bad: bafy2bzacedukrpxz37go2m5daanq7ewt5o7vlpnsqwymh6a3wk4dk6g5gunws (reason: linked to bafy2bzacebiyxbrli763o6zk7wntt5obvi5qih4jbku2iht5hkpkeonvxqgfk caused by: [bafy2bzaceactbza4qcnersz5fld7gt2azimlnftnezqug5obfkhtkilqrweio] 1 error occurred:\n\t* parent state root did not match computed state (bafy2bzacecwnbvlmn2vlnlpfeoqmrc2kkwwjq4cwvrqcog2utbizt4ozpmkny != bafy2bzacecndd4ioo3mhgi4wizs7hl62crugebkye3cvp7ikqvzxcplfmudku):\n    github.com/filecoin-project/lotus/chain/consensus.CommonBlkChecks.func3\n        /home/admfc/lotus/chain/consensus/common.go:118\n\n)"}
{"level":"warn","ts":"2024-02-04T20:34:37.329+0300","logger":"chain","caller":"chain/sync.go:218","msg":"InformNewHead called on block marked as bad: bafy2bzacedukrpxz37go2m5daanq7ewt5o7vlpnsqwymh6a3wk4dk6g5gunws (reason: linked to bafy2bzacebiyxbrli763o6zk7wntt5obvi5qih4jbku2iht5hkpkeonvxqgfk caused by: [bafy2bzaceactbza4qcnersz5fld7gt2azimlnftnezqug5obfkhtkilqrweio] 1 error occurred:\n\t* parent state root did not match computed state (bafy2bzacecwnbvlmn2vlnlpfeoqmrc2kkwwjq4cwvrqcog2utbizt4ozpmkny != bafy2bzacecndd4ioo3mhgi4wizs7hl62crugebkye3cvp7ikqvzxcplfmudku):\n    github.com/filecoin-project/lotus/chain/consensus.CommonBlkChecks.func3\n        /home/admfc/lotus/chain/consensus/common.go:118\n\n)"}
```
