### ISSUE TITLE
Reestablish the connection to PostgreSQL after encountering an error during connection

### ISSUE THREAD

**Issue by Terryhung** [filecoin-project/lily#1211]
### Description
In Lily's job, if an error occurs in the PostgreSQL connection, the job will halt and stop running. We should enable Lily to have the capability to reestablish the connection in case of an error.

### Acceptance criteria

Reconnect to PostgreSQL after terminating the connection between Lily and PostgreSQL.

**Comment by kasteph** [comment]
@Terryhung I can pick this up.
