### ISSUE TITLE
Add new column for receipt_returns: parsed_return

### ISSUE THREAD

**Issue by Terryhung** [filecoin-project/lily#1247]
### Description
Currently, the task "receipt_return" stores the return data only in bytes. Now, we are planning to store the parsed return data in JSONB format if it is parsable.
### Acceptance criteria
- New column in receipt_returns: parsed_return
### Where to begin
1. make a change: https://github.com/filecoin-project/lily/blob/master/tasks/messages/receiptreturn/task.go
2. reference: [fevm_trace](https://github.com/filecoin-project/lily/blob/master/tasks/fevm/trace/task.go#L176)

**Comment by birdychang** [comment]
I thought we wanna add them to receipts.

**Comment by Terryhung** [comment]
Good idea, let me change it again.
