### ISSUE TITLE
Code bug: Some tasks cannot obtain data

### ISSUE THREAD

**Issue by LuisCherry** [filecoin-project/lily#1280]
### Describe the bug:
Code bug: Some tasks cannot obtain data, for example: MinerSectorInfoV7
### Steps to Reproduce:
Because actorstypes Version 12 has not been added at chain/indexer/integrated/processor/state.go
![1705631517274](https://github.com/filecoin-project/lily/assets/24894725/42386ee8-855e-4a9d-b96c-631f585ad888)

 But I found that this issue does not exist on the master branch

### Lily Version: vx.x.x
v0.17.3  release

**Comment by Terryhung** [comment]
Fixed.
