### ISSUE TITLE
The two tasks of market_deal_proposal and market_deal_state are very slow ,taking approximately 6 minutes

### ISSUE THREAD

**Issue by LuisCherry** [filecoin-project/lily#1285]
### Describe the bug:
The two tasks of market_deal_proposal and market_deal_state are very slow
### Steps to Reproduce:
Trace the slow execution to this place through the code ,"chain/actors/builtin/market/diff.go",The DiffDealProposals method inside includes adt.DiffAdtArray() function executes very slowly

<img width="1033" alt="image" src="https://github.com/filecoin-project/lily/assets/24894725/eeab5820-329f-4a66-9d04-d7f68d90d33d">

**Comment by Terryhung** [comment]
@LuisCherry fixed! Please upgrade the lily to `v0.18.0`. Moreover, there is a new migration requirement.

**Comment by Terryhung** [comment]
@LuisCherry If this issue had been fixed, then I am going to close this issue.
