### ISSUE TITLE
DiffDealStates at nv22 upgrade epoch

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/lily#1291]
### Describe the bug:

at epoch 3855361 DiffDealStates went through the "slow Array comparaison" as actors are different." 
```
if requiresLegacyDiffing(pre, cur, preOpts, curOpts) {
		log.Warn("actor AMT opts differ, running slower generic array diff ", "preCID ", pre.Code(), "curCID ", cur.Code())
		if err := diff.CompareArray(preP.array(), curP.array(), diffContainer); err != nil {
			return nil, fmt.Errorf("diffing deal states: %w", err)
		}
		return diffContainer.Results, nil
	}
```

But the Diff detect 57M+ modifications : {"added":6,"modified":57377092,"removed":51},

### Steps to Reproduce:

call Diff on tipset : 3855361 and 3855362

### Lily Version: v0.18.0

Need a quick patch as we have just a few hours before our node GC, can test in a few hours if needed. 

Thank you for your support.

**Comment by s0nik42** [comment]
@ze42 @FlorianRuen

**Comment by Terryhung** [comment]
Hi @s0nik42,
Thank you for identifying this issue. In fact, having so many differences is to be expected. Otherwise, we could consider adding a condition to skip if there are too many differences. Otherwise, this data might not be meaningful.

**Comment by s0nik42** [comment]
Thanks, 
can you highlight why its expected ? If I manually analyze Filecoin.StateMArketDeals, I only see ~600 differences.

**Comment by Terryhung** [comment]
Because in those epoch, the network was during the migration to nv22. Therefore, most of them will be marked as changed.
