### ISSUE TITLE
Add a reprocess subcommand

### ISSUE THREAD

**Issue by iand** [filecoin-project/lily#152]
### Motivation & Background

Task processing is controlled by the various `visor_processing_` tables. When a task finishes an item it updates the relevant `completed_at` column and the `errors_detected` column if the processing failed. New work is selected by only selecting rows where `completed_at` is NULL. To force reprocessing we can simply update  the relevant `completed_at` columns to NULL and the item will become visible to the task processors.

Make this process easy by adding a subcommand to perform the update. The subcommand should allow:

 - type of task to reset
 - actor code (only for the actor state task)
 - reset only items that reported an error
 - a height range 
 - potentially date range for the `completed_at` column

When run the subcommand updates the relevant rows to set `completed_at` and `errors_detected` to NULL

### Acceptance Criteria

 - Can use visor to reprocess failed work for any task

**Comment by placer14** [comment]
Consider allowing for an error filter to only reset certain types of errors. It should be included in the query as a `LIKE %<filterval>%`. Also consider a `--dry-run` option which allows you to see the potential result without committing it. 🤝
