### ISSUE TITLE
Schema: Improve `derived_consensus_chain_view` for incremental refresh

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#174]
### Description
A materialized view `derived_consensus_chain_view` provides a view which describes the "heaviest" branch of the chain which the network has reached consensus on. This view is useful for queries which require the exclusion of blocks or messages which were orphaned by the consensus chain. This view is very expensive to build as it is a recursive query which needs to walk the entire chain each time its refreshed and will become more expensive over time. This view needs to allow incremental updates and cheaper initial creation.

### Acceptance criteria
- materialized view which can be incrementally updated

### Where to begin
- Prototype view `derived_consensus_chain_view`
- The key rules to apply when building this view:
  - Blocks link to explicit parent blocks
  - Blocks which are at the same height with different parent sets should prefer the block connected to the heaviest parent set as determined by `parent_weight` within the headers of the conflicting blocks. (Blocks with the same parent set should have matching `parent_weight`.)
  - Blocks should not link to a parent block which skips over blocks in the chain.

**Comment by frrist** [comment]
The goal described here will be covered as a part of #831.
