### ISSUE TITLE
Graph: Transferred Value volume per Miner over time

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#175]
### Description
As a stakeholder monitoring the Filecoin network, I want to see the volume of transferred tokens *by miners* graphed over time so I can observe trends in volume changes. I would also like to understand movement of Block Reward tokens released due to FIP-0004.

### Acceptance Criteria
- [ ] Using existing tables, craft a query which sums(value) grouped by epoch *and miner* over consensus chain (omitting forks/reorgs)
  - `messages` join (on msg cid) `block_messages` join (on block cid) `block_headers` join (on parent_state_root) `derived_consensus_chain_view`
- [ ] Create graphana panel which allows any period to be queried using previous query
- [ ] Understand how to identify the FIL-0004 tokens within this value
- [ ] Create graphana panel which isolates the FIL-0004 volume so it can be compared to the sum

**Comment by lanzafame** [comment]
@placer14 @olizilla So I was experimenting with this query the other week and it is extremely difficult to visualise in a meaningful way.

**Comment by olizilla** [comment]
Alan and I are looking at visualising this, but it's not gonna fit in Grafana. Will be a custom site with some d3. We're getting up to speed and will report back on this issue as we make progress.

**Comment by frrist** [comment]
@olizilla is still still being worked on?
