### ISSUE TITLE
VISOR_PROMETHEUS_PORT expects : before port number

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lily#333]
### Describe the bug:
[jupiter] root [/opt]# /opt/sentinel-visor/visor walk --to=300000 --from=200000                
2020-12-31T04:58:09.797+0100    FATAL   visor   commands/setup.go:268   Failed to run Prometheu
s /metrics endpoint: listen tcp :9991: bind: address already in use                            
[jupiter] root [/opt]# export VISOR_PROMETHEUS_PORT=9992                                       
[jupiter] root [/opt]# /opt/sentinel-visor/visor walk --to=300000 --from=200000                
2020-12-31T05:03:08.054+0100    FATAL   visor   commands/setup.go:268   Failed to run Prometheu
s /metrics endpoint: listen tcp: address 9992: missing port in address                         
[jupiter] root [/opt]# export VISOR_PROMETHEUS_PORT=:9992                                      
[jupiter] root [/opt]# /opt/sentinel-visor/visor walk --to=300000 --from=200000                
2020-12-31T05:03:34.331+0100    INFO    schedule        schedule/scheduler.go:124       running
 task   {"task": "ChainHistoryIndexer"} 
### Steps to Reproduce:
export VISOR_PROMETHEUS_PORT=9992
### Visor Version: vx.x.x
latest master

**Comment by PatrickDeuse** [comment]
it is documented that it needs the : 

but :Number is not a port!

**Comment by iand** [comment]
This is just a misnamed environment variable. The value sets the listen address for the prometheus export server which may be assigned to an internal network interface. We should rename the flag to `prometheus-addr` and the environment variable to `VISOR_PROMETHEUS_ADDR`

**Comment by f8-ptrk** [comment]
rename it to `prometheus-listen` . it's not an address either.

**Comment by f8-ptrk** [comment]
after deleting the previous comment i wrote i ask myself: is there a term for an ip-address:port combinations? address sounds wrong for me too - but i cannot find a term that would fit

**Comment by iand** [comment]
I normally use `addr` or `address`, following what Go's [net.Dial](https://golang.org/pkg/net/#Dial) function expects.

**Comment by frrist** [comment]
this argument is working as expected. Closing.
