### ISSUE TITLE
visor walk - extended functionality - parallel walks

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lily#338]
Hope this is the right issue type, it looked more fitting than "Bug"

as reference: https://filecoinproject.slack.com/archives/C0174P5M11T/p1609391116055600

### Description

`visor walk` currently walks the chain from `--to` to `--from` in a straight line. To speed up the processing of large sections of the chain the idea is to let `visor walk` process batches of the chain in parallel. 

Defining two new environment variables `VISOR_WALK_PARALLEL` and `VISOR_WALK_PARALLEL_BATCH_SIZE`. `visor walk` could start `VISOR_WALK_PARALLEL` walks in parallel with each processing `VISOR_WALK_PARALLEL_BATCH_SIZE` tipsets. If `VISOR_WALK_PARALLEL_BATCH_SIZE` isn't provided visor walk could just split up the range defined with `--to` and `--from` into `(--to)-(--from)/VISOR_WALK_PARALLEL` and use that as `VISOR_WALK_PARALLEL_BATCH_SIZE`. 

Note: this is possible to using more than one `visor walk` process, this here would just be a convenient functionality.

**Comment by placer14** [comment]
What is the need for the `BATCH_SIZE` that couldn't be handled with just `(--to)-(--from)/VISOR_WALK_PARALLEL` alone?

If the `BATCH_SIZE` < `(--to)-(--from)/VISOR_WALK_PARALLEL` default, should we assume any process which finishes its batch will begin completing the next batch range?

**Comment by PatrickDeuse** [comment]
> If the BATCH_SIZE < (--to)-(--from)/VISOR_WALK_PARALLEL default, should we assume any process which finishes its batch will begin completing the next batch range?

sounds reasonable. BATCH_SIZE originated in my mind before the idea of leaving it out was in it ;)

**Comment by frrist** [comment]
This has been addressed in v0.10.0 via the ability to run a distributed set of lily nodes that share work via a Redis queue.
