### ISSUE TITLE
bufbstore warns one of the stores is not viewable

### ISSUE THREAD

**Issue by iand** [filecoin-project/lily#363]
### Describe the bug:

Not sure this is a bug but in production visor logs I see this warning and I don't recognize where it's coming from

`WARN	bufbs	bufbstore/buf_bstore.go:44	one of the stores is not viewable; running less efficiently`

Seems to be reported for every tipset

### Steps to Reproduce:

Run visor watch with tasks messages, blocks, chaineconomics, actorstatesreward, actorstatesmultisig, actorstatesraw, actorstatespower

**Comment by frrist** [comment]
No longer seeing this.
