### ISSUE TITLE
List of columns and tables with low practical usefulness for monitoring and quick analysis

### ISSUE THREAD

**Issue by hsanjuan** [filecoin-project/lily#503]
Seeing that we should try to make the pressure on Postgres caused by sentinel as light as possible, here is a list of columns that I would probably not notice if they were dropped from the schema.

We are not going to drop this columns as we want to capture as much data as possible, but we might provide the option to use a "light" version of the schema that stores less data.

* actor_states: code (not sure what to do with it in sentinel).
* actors: nonce and state_root
* block_headers: timestamp, parent_state_root
* block_parents: could live without this table altogether
* chain_economics: consider adding height and removing parent_state_root
* chain_powers: state_root
* chain_rewards: state_root
* derived_gas_outputs: state_root, nonce
* id_addresses: state_root
* market_deal_proposals: state_root, slashed_epoch (already in deal_states), label
* market_deal_states: state_root,  sector_start_epoch (assuming corresponds to the height of first entry for a deal_id in the table), last_update_epoch (assuming corresponds to the last entry for a deal_id in the table)
* messages: I could mostly live without messages and just use derived_gas_outputs and parsed_messages.
* message_gas_economy: state_root
* messages: gas_fee_cap, gas_premium, gas_limit (these are in derived_gas_outputs for all messages that attempt execution), nonce
* miner_current_deadline_infos: state_root
* miner_fee_debts: state_root
* miner_infos: state_root
* miner_locked_funds: state_root
* miner_pre_commit_infos: state_root
* miner_sector_events: state_root
* miner_sector_infos: state_root
* multisig_approvals: state_root
* multisig_transactions: state_root
* power_actor_claims: state_root
* receipts: I could live without receipts, having derived_gas_outputs which contains exit_code etc.
* sector_precommit_info: state_root.

I am suspecting that dropping `*state_root` columns would save a great deal of space. This would be useful with forks when trying to discriminate data etc, but in practice, when running with enough confidence, we don't have this problem and for analysis and monitoring it is mostly useless since we always work with height, sum by height etc.

**Comment by frrist** [comment]
closing in favor of https://github.com/filecoin-project/lily/issues/933
