### ISSUE TITLE
visor daemon tipset processing around 15s slower then lotus

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lily#553]
### Describe the bug:

running `visor daemon` processes tipsets in around 15-20s while the lotus fullnode needs less then 1s

if a walk runs the tipset processing time goes up to > 45s

this results in an out of sync node when `visor daemon` is used - running via api lens on a lotus daemon it stays in sync

**Comment by iand** [comment]
Can you provide more information on the tasks being run on the visor node?

**Comment by f8-ptrk** [comment]
none

and then a walk task

**Comment by iand** [comment]
What tasks were specified for the walk?

**Comment by f8-ptrk** [comment]
blocks, messages

**Comment by iand** [comment]
How are you measuring the processing time? Over what period were the measurements taken? Before a job runs there should be almost no overhead from visor since we don't hook into the event subsystem until the first job is started.

**Comment by frrist** [comment]
Messages and blocks have all been processed within a second for the past few weeks. Going to close this as there isn't enough info to debug the problem.
<img width="1706" alt="Screen Shot 2022-02-01 at 3 21 42 PM" src="https://user-images.githubusercontent.com/6546409/152068056-86b121a5-3d07-416f-ac5b-c18ada770d69.png">
