### ISSUE TITLE
Block not found when lily bootstrapped from minimal finality carfile

### ISSUE THREAD

**Issue by iand** [filecoin-project/lily#562]
### Describe the bug:

Visor daemon emits `block not found` in log when diffing actor states on a node bootstrapped from a minimal finality carfile.

### Steps to Reproduce:

Download minimal finality stateroots export, import into a fresh visor install and then start:
```
aria2c -x8 https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car
visor daemon --repo=/data/lily_data --import-snapshot=minimal_finality_stateroots_latest.car
visor daemon --repo=/data/lily_data --config=/data/lily_data/config.toml
```

Daemon runs and syncs with network

Run  a watch that includes actor states:

```
visor watch --confidence=5 --tasks=actorstatesminer
```
Wait and see multiple instances of block not found error logged:

```
state/statetree.go:275	failed to load state tree: failed to load hamt node: blockstore: block not found
```

Stop the node and import from [complete_chain_with_finality_stateroots_latest.car](https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/complete_chain_with_finality_stateroots_latest.car) and the block not found error will be fixed.

### Visor Version: vx.x.x

https://github.com/filecoin-project/sentinel-visor/commit/ab9e7de2f86848dc94c9ad2803690527db1c1a42

**Comment by hsanjuan** [comment]
Does it only happen with actorstatesminer?

**Comment by iand** [comment]
> Does it only happen with actorstatesminer?

I don't know, didn't spend any extra time investigating at this stage

**Comment by tuzkii** [comment]
![image](https://user-images.githubusercontent.com/6689676/131800444-5add4c34-2b8b-484a-a9b1-6d33cb553b5b.png)

**Comment by frrist** [comment]
I believe we have opted for using full state snapshots. I have filed https://github.com/filecoin-project/lily/issues/832 to debug issues like this if they arise in the future.
