### ISSUE TITLE
Replace calls to PriceListByEpoch with PriceListByVersion

### ISSUE THREAD

**Issue by iand** [filecoin-project/lily#600]
Lotus is planning to remove PriceListByEpoch which visor uses to calculate gas prices. We should replace with the alternative PriceListByVersion. See https://github.com/filecoin-project/lotus/pull/6766

**Comment by frrist** [comment]
We don't use `PriceListByEpoch` within lily. Am I missing it somewhere?

**Comment by frrist** [comment]
Closing, based on above comment
