### ISSUE TITLE
Implement internal message filtering

### ISSUE THREAD

**Issue by frrist** [filecoin-project/lily#602]
### Description
https://github.com/filecoin-project/sentinel-visor/pull/533 implements internal message extraction, but doesn't go all the way in that it only extracts Block Reward and Cron Tick messages. This issue is a placeholder to implement filtering on the internal message task such that messages may be extracted based on some filter

### Where to begin
https://github.com/filecoin-project/sentinel-visor/pull/533/files#diff-a6d019bccf2350a6a76e816e98e5001f313bf37d66172abf0175374db6bedbc9R100-R160

**Comment by Schwartz10** [comment]
@frrist continuing the conversation from [slack](https://filecoinproject.slack.com/archives/C0174P5M11T/p1638456381267000)...

Glif is redoing its transaction history, and we'd like to surface "relevant" information/messages about an address. We're trying to define "relevancy", but my gut feeling is: "any message to/from this address, and any _internal_ message that changes this address' balance". 

What are your thoughts on that? How would you define "relevancy" in this context? How does that change when general FVM programmability gets released next year?

I've been looking at Etherscan for inspiration too, wondering how/what they're reporting:

![image](https://user-images.githubusercontent.com/12353734/144627957-e76e3658-8ef1-4086-88f9-5a4786ff5145.png)
![image](https://user-images.githubusercontent.com/12353734/144628002-70ec8d61-5fa0-47c4-82a2-7e46f7729af6.png)

**Comment by frrist** [comment]
@Schwartz10 thanks for the added context, it's caused me to re-think this a bit. 
Given the use case of tracking balance changes to different actors I think it will be best to track all internal message sends and perform the filtering over the extracted data. Additionally for those consuming sentinel-archive data it will be hard to know in advance which actors are interesting, better to track them all.

> How does that change when general FVM programmability gets released next year?

Ideally it doesn't change much wrt lily, but I am not sure at this point.

I am going to start working on this now (many folks are asking for data in this vein), will share when I have something ready.

**Comment by Schwartz10** [comment]
@frrist when you say:

> track all internal message sends

Do you mean specifically "all internal messages that get executed" or just "internal _transfer_ messages"? 

I'm assuming you mean the former, but just want to be sure I understand. In this case, do we think this is going to make the timescaleDB enormous in scale?

**Comment by frrist** [comment]
Right now I am thinking the former, but this could change -- I need to dig in a bit more. Yes this will increase the overall size of the database, not sure there is a good way around that other than filtering out the messages that we are pretty sure no one will ever want, but that's hard to determine in advance.

**Comment by frrist** [comment]
Will be simpler to filter unwanted messages from database once extracted. Work for internal message extraction exists here: https://github.com/filecoin-project/lily/issues/865. Closing
