### ISSUE TITLE
Visor walk job does not appear to be manageable once completed

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#608]
### Describe the bug:

Completed `walk` jobs cannot be restarted using the `job start` command.

### Steps to Reproduce:

1. A `walk` job was started with the following args: `--window=10m --from=944880 --to=959280 --tasks=blocks,messages,chainecono    mics,actorstatesraw,actorstatespower,actorstatesminer,actorstatesreward,actorstat    esinit,actorstatesmarket,actorstatesmultisig,msapprovals`
2. The job completed as expected.
3. Attempting to start the job again did not change the Running state from `false` to `true` as expected. (using `visor job start --id=<ID>`)

**Comment by iand** [comment]
Were there any other log entries. From the code I would expect to see `starting worker ID: xx not found` if the job had been removed, `starting worker ID: xx already running` if it hadn't been marked as finished and `starting job` otherwise. We also log a metric `job_start` when it starts (as well as `job_complete`, `job_error` and `job_timeout`)

**Comment by frrist** [comment]
Appears to be working as expected on current master. Going to close.
```
frrist@oak ~/W/s/g/f/lily (master)> ./lily job list
[
	{
		"ID": 1,
		"Name": "walk_1643761293",
		"Type": "walk",
		"Error": "",
		"Tasks": [
			"blocks"
		],
		"Running": false,
		"RestartOnFailure": false,
		"RestartOnCompletion": false,
		"RestartDelay": 0,
		"Params": {
			"maxHeight": "10",
			"minHeight": "0",
			"storage": "Database1",
			"window": "5m0s"
		},
		"StartedAt": "2022-02-02T00:23:29.969018Z",
		"EndedAt": "2022-02-02T00:23:30.038139Z"
	}
]
frrist@oak ~/W/s/g/f/lily (master)> ./lily job start --id 1; and ./lily job list
[
	{
		"ID": 1,
		"Name": "walk_1643761293",
		"Type": "walk",
		"Error": "",
		"Tasks": [
			"blocks"
		],
		"Running": true,
		"RestartOnFailure": false,
		"RestartOnCompletion": false,
		"RestartDelay": 0,
		"Params": {
			"maxHeight": "10",
			"minHeight": "0",
			"storage": "Database1",
			"window": "5m0s"
		},
		"StartedAt": "2022-02-02T00:23:45.039935Z",
		"EndedAt": "0001-01-01T00:00:00Z"
	}
]
frrist@oak ~/W/s/g/f/lily (master)> ./lily job list
[
	{
		"ID": 1,
		"Name": "walk_1643761293",
		"Type": "walk",
		"Error": "",
		"Tasks": [
			"blocks"
		],
		"Running": false,
		"RestartOnFailure": false,
		"RestartOnCompletion": false,
		"RestartDelay": 0,
		"Params": {
			"maxHeight": "10",
			"minHeight": "0",
			"storage": "Database1",
			"window": "5m0s"
		},
		"StartedAt": "2022-02-02T00:23:45.039935Z",
		"EndedAt": "2022-02-02T00:23:45.107352Z"
	}
]
```
