### ISSUE TITLE
Issue with early market_deal_proposals exports

### ISSUE THREAD

**Issue by thattommyhall** [filecoin-project/lily#619]
### Describe the bug:

I tried to insert the csv's made with `walk` for `market_deal_proposals` and get a bunch of the following errrors for daily ranges between 

40560__43440
and
98160__101040

```
ERROR:  invalid byte sequence for encoding "UTF8": 0xa1
```

### Steps to Reproduce:

Inside psql with PWD `/output/airflow-backfill-csvonly/40560__43440` 

```
BEGIN TRANSACTION;CREATE TEMP TABLE backfill_temp_market_deal_proposals ON COMMIT DROP AS SELECT * FROM visor.market_deal_proposals WITH NO DATA;                                             
copy backfill_temp_market_deal_proposals(height,deal_id,state_root,padded_piece_size,unpadded_piece_size,start_epoch,end_epoch,client_id,provider_id,client_collateral,provider_collateral,sto
rage_price_per_epoch,piece_cid,is_verified,label) FROM 'market_deal_proposals.csv' DELIMITER ',' CSV HEADER;                                                                                  
INSERT INTO visor.market_deal_proposals SELECT * FROM backfill_temp_market_deal_proposals ON CONFLICT DO NOTHING;COMMIT;    
```

### Visor Version: 

I'm afraid I can't be certain, I can rerun with the lastest and check if it still happens though.

**Comment by hsanjuan** [comment]
The label column looks like this on a problematic csv:

![image](https://user-images.githubusercontent.com/1027022/128739940-2bbdbadb-d631-4f38-b421-bcdca4143aa4.png)

On the previous one which gives no problems:

![image](https://user-images.githubusercontent.com/1027022/128739990-09f161b9-70d2-4573-b160-89023d026ecb.png)

Worth a re-run.

**Comment by iand** [comment]
Fixed by https://github.com/filecoin-project/lily/issues/843
