### ISSUE TITLE
Lily API can reflect taskload readiness

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#641]
### Description

As a visor operator, I would like to know when the node is in a ready state for the Jobs it is configured to perform. This is useful to reflect on the ability of the instance to act on tasks requested of it. Specifically, this should completely close the remaining downtime gap for deployments, open the door to support finer-grained failover handling, and allow other interesting programmatic handling requiring this type of reflection.

The ultimate goal of being operationally ready is have an endpoint which returns a bool when every job visor is performing is actively able to write to the DB. I realize there's a lot of nuance here so I will try to clarify all of the cases which constitute being ready:

### Acceptance criteria

(updated 10/12/21)

Requirements adjusted to a smaller initial scope, as follows:

- A. "ready" is achieved when
  - 1. chain has synced
  - 2. has at more than zero tasks running with its confidence cache filled
  - 3. has all tasks running with its confidence cache filled only if multiple tasks have been scheduled and the node has not become previously "ready"
- B. an API endpoint which responds `200 OK` w a payload `{"ready": true}` when "ready" for the first time and every time afterward (i.e.: service state changing will not change API response after becoming "ready")
- C. ....which responds `503 Service Unavailable` w a payload `{"ready": false}` before being "ready"

### Where to begin

TBD

**Comment by frrist** [comment]
Here's where I would  look to begin with: https://github.com/filecoin-project/sentinel-visor/blob/15036b86ecfcfa29965a7df4c14a21363262c343/chain/indexer.go#L426-L454

The API will return `true`/`ready` iff the Visor daemon is running and all active jobs have persisted data to storage, correct?

**Comment by frrist** [comment]
This has gotten stale, @placer14 please feel free to reopen when you are ready to take a swing at it.

**Comment by placer14** [comment]
No problem. Thanks for cleaning this up. I will attempt to solve this as an operational problem and see if there is still any need from Lily on this once I spend more time here. 🙇
