### ISSUE TITLE
Watch jobs don't stop correctly

### ISSUE THREAD

**Issue by iand** [filecoin-project/lily#658]
### Describe the bug:

Stopping a watch job causes the job to hang and seems to prevent new watch jobs from starting

**Comment by frrist** [comment]
caused by https://github.com/filecoin-project/lotus/pull/8441, once this lands in a release and https://github.com/filecoin-project/lily/blob/dbbc764e5f16ac943506b4d67bb48d6888c79b76/chain/watcher.go#L89 is addressed we can close this
