### ISSUE TITLE
Walks should handle null round at upper bound

### ISSUE THREAD

**Issue by iand** [filecoin-project/lily#659]
### Describe the bug:

Currently `chain.Walker` fetches the tipset at the following height to the upper bound to start the walk. This will fail to process the last tipset in the range if there is a null round a maxHeight+1. Use `ChainGetTipSetAfterHeight` instead of incrementing the height.

**Comment by frrist** [comment]
closed via #589 - https://github.com/filecoin-project/lily/pull/598/files#diff-c238b905b2ddf4664243de2f17803fda6ead675863ba9e0d5b6d966012d46abcR60
