### ISSUE TITLE
Processing error: unknown parameters for b

### ISSUE THREAD

**Issue by iand** [filecoin-project/lily#660]
### Describe the bug:

messages task sometimes fails with the error `failed to parse message params: unknown parameters for b`

### Steps to Reproduce:

Examples from logs

956422,bafy2bzacec4i3dwswste5yiet5a6ihiznzdcsekw46xstmlr3iew5ynuxipbw,visor,messages,2021-07-25T02:53:39.601Z,2021-07-25T02:53:39.633Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzaceamxxkg3lpba7w5k3yufklizf5kixryhrzgjpg3udscqmplft4jqo""},""Error"":""failed to parse message params: unknown parameters for b""}]"

994599,bafy2bzaceb4qrhwsz3pduqsfgmcsvkbzcv3zqbwnpxseeikdpkozl7vitkj5g,visor,messages,2021-08-09T20:19:34.975Z,2021-08-09T20:19:35.002Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzaced4ystr2243xfi6zow4iscuc74l4addtkx67ojgc7kyajoy56fooo""},""Error"":""failed to parse message params: unknown parameters for b""}]"

994594,bafy2bzaceb6np2v6mlw3gmddnfutg4emd2f5vhlv5vci3mowjiyv76sicwta2,visor,messages,2021-08-09T20:21:26.279Z,2021-08-09T20:21:26.309Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzaceb54a6mnwequyjyv3alej6vvnsiggsnmo45ykqgax5vnm2hgi26zm""},""Error"":""failed to parse message params: unknown parameters for b""}]"

**Comment by frrist** [comment]
My first hunch is the CID being printed is `Undef`: https://play.golang.org/p/29lj5ppSn5X

**Comment by iand** [comment]
Message bafy2bzaceamxxkg3lpba7w5k3yufklizf5kixryhrzgjpg3udscqmplft4jqo at height 956422 was in block bafy2bzaceckmhfo65uoyxf2asao4szr3hz55fbn7atnssm2j6whax7arhnpok. 

It has null params:

```
    {
      "Version": 0,
      "To": "f2vpxvw7yq44fhvdkui2akhwvxv5273m236n2c5cq",
      "From": "f3wbace5sk23trrchniluluyju3gokmashc3uugkn77z643kv7n7rqmkfojkaf4dcw6w3f5jaew472fogcs7iq",
      "Nonce": 3363,
      "Value": "0",
      "GasLimit": 678176,
      "GasFeeCap": "1857478298",
      "GasPremium": "100584",
      "Method": 4,
      "Params": null,
      "CID": {
        "/": "bafy2bzaceamxxkg3lpba7w5k3yufklizf5kixryhrzgjpg3udscqmplft4jqo"
      }
    },

```

Method 4 on the payment channel actor is Collect which does not expect params. Looks like we should detect and handle this case.

**Comment by iand** [comment]
Actually this error is returned when the actor code is unknown

**Comment by iand** [comment]
This is caused by the GetExecutedAndBlockMessagesForTipset being unable to find the actor code for the recipient of the message. This results in cid.Undef being used in the To field of the message, which the message parser then uses to look up the method table. I re-ran this and verfied following warning was logged:

2021-08-19T09:32:21.101Z        WARN    lens/util       util/repo.go:321        failed to find TO actor {"height": "956423", "message": "bafy2bzaceamxxkg3lpba7w5k3yufklizf5kixryhrzgjpg3udscqmplft4jqo", "actor": "f2vpxvw7yq44fhvdkui2akhwvxv5273m236n2c5cq"}

**Comment by iand** [comment]
Its seems the actor `f2vpxvw7yq44fhvdkui2akhwvxv5273m236n2c5cq`  (`f047414`) cannot be found in the state tree at either epoch 956422 or 956423. It is not returned by the ForEach we use [here](https://github.com/filecoin-project/sentinel-visor/blob/master/lens/util/repo.go#L501) and adding a direct GetActor call also fails with an `actor not found` error.

However this actor does exist and the message `bafy2bzaceamxxkg3lpba7w5k3yufklizf5kixryhrzgjpg3udscqmplft4jqo` executed successfully. The actor was created at epoch 164006 and has received two other messages at epochs 953081 and 953089. See https://filfox.info/en/address/f2vpxvw7yq44fhvdkui2akhwvxv5273m236n2c5cq

**Comment by iand** [comment]
Verified that messages `bafy2bzaced4ystr2243xfi6zow4iscuc74l4addtkx67ojgc7kyajoy56fooo` and `bafy2bzaceb54a6mnwequyjyv3alej6vvnsiggsnmo45ykqgax5vnm2hgi26zm` are failing for the same reason: the to actor cannot be found in the state tree. These messages have the same actor address: `f1j6dml3u44xzszmr5jsc5izpg5uzdnpa5oql6bmy` 

`lotus state get-actor f1j6dml3u44xzszmr5jsc5izpg5uzdnpa5oql6bmy` is successful for this actor

**Comment by iand** [comment]
Same cause as #662: payment channels delete themselves once settled.
