### ISSUE TITLE
Processing error: AssignBytes called on a types.ApplyRewardParams.Repr

### ISSUE THREAD

**Issue by iand** [filecoin-project/lily#661]
### Describe the bug:

messages task sometimes fails with the error `failed to parse message params: cbor decode into ApplyRewards (bafkqaetgnfwc6mjpon2g64tbm5sw22lomvza.14) failed: func called on wrong kind: AssignBytes called on a types.ApplyRewardParams.Repr node (kind: list), but only makes sense on bytes`

### Steps to Reproduce:

Examples from logs

100297,bafy2bzacec3cr5kovp22syvikmqxxchwflw4hdrlq6cypqhz43dj6pjwm3ox4,visor,messages,2021-06-11T21:43:46.228Z,2021-06-11T21:43:46.554Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzacecqp55nmquhtzhxklqnceckwy36xlypc35wfydgaqluda5hntdzku""},""Error"":""failed to parse message params: cbor decode into ApplyRewards (bafkqaetgnfwc6mjpon2g64tbm5sw22lomvza.14) failed: func called on wrong kind: AssignBytes called on a types.ApplyRewardParams.Repr node (kind: list), but only makes sense on bytes""}]"

99572,bafy2bzacec3yculkyrnx5ic7pa456ovc3j7fzxcq2lbfdj5unscq4tqq4jboy,visor,messages,2021-06-11T22:08:19.551Z,2021-06-11T22:08:19.849Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzacecsre4wamcb5vbfiue2wk53hawglsfzsrw64qqfr6aqqxs5g37tlw""},""Error"":""failed to parse message params: cbor decode into ApplyRewards (bafkqaetgnfwc6mjpon2g64tbm5sw22lomvza.14) failed: func called on wrong kind: AssignBytes called on a types.ApplyRewardParams.Repr node (kind: list), but only makes sense on bytes""},{""Cid"":{""/"":""bafy2bzacece3kv53crfl72jodeuzttbudv63lqddknermqy3pz7ddq354mvhg""},""Error"":""failed to parse message params: cbor decode into ApplyRewards (bafkqaetgnfwc6mjpon2g64tbm5sw22lomvza.14) failed: func called on wrong kind: AssignBytes called on a types.ApplyRewardParams.Repr node (kind: list), but only makes sense on bytes""}]"

**Comment by frrist** [comment]
via https://github.com/filecoin-project/lily/pull/799
