### ISSUE TITLE
Visor watch does not write to database

### ISSUE THREAD

**Issue by zaczzy** [filecoin-project/lily#673]
### Describe the bug:
After i waited for `visor sync wait` to complete, 
I cannot get visor to successfully write to database. 

config.toml:
```
[Metrics]
#  Nickname = ""
#  HeadNotifs = false
#
[Wallet]
#  RemoteBackend = ""
#  EnableLedger = false
#  DisableLocal = false
#
[Fees]
#  DefaultMaxFee = "0.07 FIL"
#
[Chainstore]
#  EnableSplitstore = false
#  [Chainstore.Splitstore]
#    HotStoreType = "badger"
#    TrackingStoreType = ""
#    MarkSetType = ""
#    EnableFullCompaction = false
#    EnableGC = false
#    Archival = false
#
[Storage]
  [Storage.Postgresql]
    [Storage.Postgresql.Database1]
      URL = "postgres://postgres:password@localhost:5432/postgres?sslmode=disable"
      ApplicationName = "visor-lily"
      SchemaName = "public"
      PoolSize = 60
      AllowUpsert = false
```
I ran `visor watch --storage=Database1 --tasks=messages,blocks,chaineconomics --window=60s --confidence 10` 
but it does not write to my local database running on localhost.

### Steps to Reproduce:
I ran visor from official container [https://hub.docker.com/layers/filecoin/sentinel-visor/v0.7.5/images/sha256-1bdd51ada6ab38a9e6965387a03c781abb46f784f64fd3d3852fdf4a74256f31?context=explore](https://hub.docker.com/layers/filecoin/sentinel-visor/v0.7.5/images/sha256-1bdd51ada6ab38a9e6965387a03c781abb46f784f64fd3d3852fdf4a74256f31?context=explore)
The network mode should be `--network=host`.

And I ran timescaledb using the docker-compse.yaml at master branch with `docker-compose up --build timescaledb`.
I tested that timescaledb is able to receive connections, so it must be visor or network.

**Comment by iand** [comment]
When you run `visor daemon --config=<path to config>` do you see a log line that reports the storage has been registered. It should be very early on, something like this:

`DEBUG   visor/storage   storage/catalog.go:27   registering storage     {"name": "Database1", "type": "postgresql"}`

Also can you confirm that you can access your local postgres database using `psql postgres://postgres:password@localhost:5432/postgres?sslmode=disable`

**Comment by zaczzy** [comment]
Ah I don't see the DEBUG log line you mentioned, even though the last 3 of the first 30000 lines of logs are 
```
2021-08-20T23:51:51.512Z        DEBUG   badgerbs        v2@v2.2007.2/levels.go:656      LOG Compact. Added 829211 keys. Skipped 0 keys. Iteration took: 324.852085ms
2021-08-20T23:51:51.577Z        WARN    vm      vm/runtime.go:350       Abortf: failed to process post submission for deadline 26: partition already proven: {{[12] false} map[] map[]}
2021-08-20T23:51:51.577Z        WARN    vm      vm/runtime.go:149       VM.Call failure: failed to process post submission for deadline 26: partition already proven: {{[12] false} map[] map[]} (RetCode=16):
```
I think that's indicative that I did not run `daemon` correctly. I did not, in fact, add the `--config` flag to daemon. Silly. Let me stop and run daemon again.

For your second suggest, I have been able to connect to this containerized timescaledb on EC2 from even my local computer. (I was able to run `\dt+` and see most tables with very small size. It's how I know visor is not writing.) 
So I think DB rejecting connection may not be the case. I also did not detect any errors from the postgres daemon.

**Comment by zaczzy** [comment]
Thank so much Ian, that was my issue. Closing this.
