### ISSUE TITLE
No replacement for VISOR_WALK_TASKS

### ISSUE THREAD

**Issue by thattommyhall** [filecoin-project/lily#698]
### Describe the bug:

I use VISOR_WALK_TASKS to control what tasks run for targeted re-runs. I need to use ENV vars as the commandline is baked into the Docker image

**Comment by frrist** [comment]
This was previously on the `run` command which has been removed. This fix is to add it here: https://github.com/filecoin-project/lily/blob/master/commands/walk.go#L35 via the `EnvVars` field.
