### ISSUE TITLE
Optimize suggestion: cache mechanism for getActorCode

### ISSUE THREAD

**Issue by bugs-404** [filecoin-project/lily#700]
Some cache mechanism should be helpful to speed up this function call

1、make `actorCodes` global cached
2、for an actor check if actorCodes[actor] is exist. return the cid if exist otherwise fall back to looking in current state tree and save the result to cache.

https://github.com/filecoin-project/lily/blob/07644efdcd752a626c1efdf256070419e3780f1a/lens/util/repo.go#L244

**Comment by frrist** [comment]
via https://github.com/filecoin-project/lily/blob/v0.8.8/commands/daemon.go#L154-L165
