### ISSUE TITLE
f8-ptrk lily tryout note thread

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lily#702]
### Describe the bug:

https://github.com/filecoin-project/lily/blob/1851e3ffe2778c345c534ceab23cc837b050b24b/docs/deployment_ops_guide.md#operating-lily claims the repo folder stores the param files. thats not true. they are stored in /var/tmp 

how to define the path for params? as in lotus? needs to be documented!

### Visor Version: vx.x.x
v0.8.0

**Comment by f8-ptrk** [comment]
i just add on here @placer14 

https://github.com/filecoin-project/lily/blob/1851e3ffe2778c345c534ceab23cc837b050b24b/docs/deployment_ops_guide.md#option-initialize-repo-path claims:

`If a directory already exists at the location, it will be untouched by lily init.` thats false. it might not touch an existing repo - if the folder exists and is empty the repo is created in the folder

**Comment by f8-ptrk** [comment]
https://github.com/filecoin-project/lily/blob/1851e3ffe2778c345c534ceab23cc837b050b24b/docs/deployment_ops_guide.md#logging

`explore GOLOG_LOG_LEVEL="debug"` export

**Comment by f8-ptrk** [comment]
FIL_PROOFS_PARAMETER_CACHE=/home/filecoin/main/param-cache
and maybe FIL_PROOFS_PARENT_CACHE=/home/filecoin/main/parent-cache


are the values to define where the cache should be, tested on v0.8.0

**Comment by f8-ptrk** [comment]
default config file includes mentions of visor in the [Storage] section

**Comment by f8-ptrk** [comment]
lily doesn't start when the db string is wrong in the [Storage] section

i will use this here to write down the findings and then fan them out later into issues or fix the trivial stuff right away.

 thanks for understanding

**Comment by f8-ptrk** [comment]
lily leaks auth token in help output

![2021-09-11_22-08](https://user-images.githubusercontent.com/60559388/132950630-60a5be20-e427-420e-80cc-31fca125cb5f.png)

**Comment by f8-ptrk** [comment]
it be nice to have the job RTT in this view!

![2021-09-12_10-03](https://user-images.githubusercontent.com/60559388/132968174-7191caba-fe8a-4e95-8297-58ec367eeca3.png)

**Comment by frrist** [comment]
via https://lilium.sh/software/lily/operation/
