### ISSUE TITLE
Error: "amt load: failed to root: blockstore: block not found"

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#718]
### Describe the bug:

```
amt load:
    github.com/filecoin-project/lily/lens/util.GetExecutedAndBlockMessagesForTipset
        /go/src/github.com/filecoin-project/lily/lens/util/repo.go:136
  - failed to root:
    github.com/filecoin-project/specs-actors/actors/util/adt.AsArray
        /go/pkg/mod/github.com/filecoin-project/specs-actors@v0.9.14/actors/util/adt/array.go:24
  - blockstore: block not found
```

Error examples:

1. `{"level":"error","ts":"2021-09-22T18:50:46.408Z","logger":"lily/chain","caller":"chain/indexer.go:281","msg":"failed to extract messages","current":1133121,"next":1133122,"error":"amt load: failed to root: blockstore: block not found","errorVerbose":"amt load:\n github.com/filecoin-project/lily/lens/util.GetExecutedAndBlockMessagesForTipset\n /go/src/github.com/filecoin-project/lily/lens/util/repo.go:136\n - failed to root:\n github.com/filecoin-project/specs-actors/actors/util/adt.AsArray\n /go/pkg/mod/github.com/filecoin-project/specs-actors@v0.9.14/actors/util/adt/array.go:24\n - blockstore: block not found"}`
2. `{"level":"warn","ts":"2021-10-05T18:25:04.449Z","logger":"chainxchg","caller":"exchange/client.go:128","msg":"processing
 peer 12D3KooWAXeUbVCwcMqMqS8et8SZLm87LchRMDbBBw1AT5yyn9dP response 
failed: status <mark>error</mark>: block sync peer errored: gather 
messages failed: loading bls message cids for block: failed to traverse 
amt: blockstore: block not found"}` (note: [this is the same peerid appear in this error](https://github.com/filecoin-project/lily/issues/727) and may be related)

### Steps to Reproduce:

This was executed on our internal mainnet analysis DB over all heights in the DB with a node which was intantiated from `https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car` on Sept 22 (so the state would not necessarily cover all heights covered in the gapfill).

The job report from the fill which produced this error:
```
        {
                "ID": 3,
                "Name": "initial-fill-03-806642-1133772",
                "Type": "Fill",
                "Error": "",
                "Tasks": [
                        "actorstatesmultisig",
                        "actorstatespower",
                        "actorstatesraw",
                        "actorstatesreward",
                        "actorstatesverifreg",
                        "blocks",
                        "chaineconomics",
                        "consensus",
                        "implicitmessage",
                        "messages",
                        "msapprovals",
                        "actorstatesinit",
                        "actorstatesmarket"
                ],
                "Running": false,
                "RestartOnFailure": false,
                "RestartOnCompletion": false,
                "RestartDelay": 0,
                "Params": {
                        "maxHeight": "1133772",
                        "minHeight": "806642",
                        "storage": "db"
                },
                "StartedAt": "2021-09-24T03:55:14.323816903Z",
                "EndedAt": "2021-09-24T04:00:22.414538928Z"
        }
```

Unsure what else would be helpful here, but can add as needed.

**Comment by iand** [comment]
The log should have a height associated with it. This is the kind of error you would get if there was not a full state tree available at a particular height.

**Comment by placer14** [comment]
```
{"level":"error","ts":"2021-09-22T18:50:46.408Z","logger":"lily/chain","caller":"chain/indexer.go:281","msg":"failed to extract messages","current":1133121,"next":1133122,"error":"amt load: failed to root: blockstore: block not found","errorVerbose":"amt load:\n    github.com/filecoin-project/lily/lens/util.GetExecutedAndBlockMessagesForTipset\n        /go/src/github.com/filecoin-project/lily/lens/util/repo.go:136\n  - failed to root:\n    github.com/filecoin-project/specs-actors/actors/util/adt.AsArray\n        /go/pkg/mod/github.com/filecoin-project/specs-actors@v0.9.14/actors/util/adt/array.go:24\n  - blockstore: block not found"}
```

The node was instatiated at `2021-09-23T23:26:44-04:00` with whatever stateroots were imported from the `https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car` file available at that time.

It seems the next step is to try again with `https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/complete_chain_with_finality_stateroots_latest.car`. Doing that now and will report back today.

**Comment by placer14** [comment]
This is likely due to the node not having state to find the block in its datastore due to node being initialized with the recent snapshot. Going to close this for now assuming this was the problem (which is not a supported use case). Will reopen if we suspect this is due to anothe reason.

**Comment by frrist** [comment]
If there is a bug in GapFill, I'd like to investigate and fix it, but I struggle to find the relationship between failing to sync with another node on the network and GapFill. Are there any new logs from Lily (the latest is a lotus log)?  

The [latest](https://github.com/filecoin-project/lily/issues/718#issuecomment-934744520) indicates that peer `12D3KooWAXeUbVCwcMqMqS8et8SZLm87LchRMDbBBw1AT5yyn9dP` doesn't have the TipSet requested by Lily, and https://github.com/filecoin-project/lily/issues/727 indicates Lily doesn't have the TipSet peer `12D3KooWAXeUbVCwcMqMqS8et8SZLm87LchRMDbBBw1AT5yyn9dP` is requesting. Maybe we are on different chains, especially if it's just this one peer? :man_shrugging:

**Comment by placer14** [comment]
Could it be that this occurs when the node is missing the state to load? I have a node which is trying to load a height from before the node was initialized and it's failing similarly but with a different trace:
```
load state tree:
    github.com/filecoin-project/lily/lens/util.MakeGetActorCodeFunc
        /go/src/github.com/filecoin-project/lily/lens/util/repo.go:247
  - failed to load state tree bafy2bzacecrouzqzcn5lhzt2olran6umt6whdpf4b4we3qqcl6ertffkk4atm:
    github.com/filecoin-project/lotus/chain/state.LoadStateTree
        /go/pkg/mod/github.com/filecoin-project/lotus@v1.13.0/chain/state/statetree.go:276
  - failed to load hamt node:
    github.com/filecoin-project/specs-actors/actors/util/adt.AsMap
        /go/pkg/mod/github.com/filecoin-project/specs-actors@v0.9.14/actors/util/adt/map.go:41
  - blockstore: block not found
  ```

**Comment by frrist** [comment]
> I have a node which is trying to load a height from before the node was initialized and it's failing similarly but with a different trace

This seems to be the case. closing
