### ISSUE TITLE
Errors from gapfill and gapfind are not persisted to visor_processing_reports

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#726]
### Describe the bug:

Results from gapfill and gapfind tasks do not include error details when they are reported. Here's a CSV dump of a few of those records:

```
reporter	task	status	status_information	errors_detected
lily-production-mainnet-analysis-gapfill/gapfill-/t=Sin,f=1149120,t=1152240	actorstatesinit	ERROR		{}
lily-production-mainnet-analysis-gapfill/gapfill-/t=Sma,f=1149120,t=1152240	actorstatesmarket	ERROR		{}
lily-production-mainnet-analysis-gapfill/gapfill-/t=SmuSpoSraSreSveblchcoimmems,f=1149120,t=1152240	actorstatesmultisig	ERROR		{}
lily-production-mainnet-analysis-gapfill/gapfill-/t=SmuSpoSraSreSveblchcoimmems,f=1149120,t=1152240	actorstatespower	ERROR		{}
lily-production-mainnet-analysis-gapfill/gapfill-/t=SmuSpoSraSreSveblchcoimmems,f=1149120,t=1152240	actorstatesraw	ERROR		{}
lily-production-mainnet-analysis-gapfill/gapfill-/t=SmuSpoSraSreSveblchcoimmems,f=1149120,t=1152240	actorstatesreward	ERROR		{}
lily-production-mainnet-analysis-gapfill/gapfill-/t=SmuSpoSraSreSveblchcoimmems,f=1149120,t=1152240	actorstatesverifreg	ERROR		{}
lily-production-mainnet-analysis-gapfill/gapfill-/t=SmuSpoSraSreSveblchcoimmems,f=1149120,t=1152240	implicitmessage	ERROR		{}
lily-production-mainnet-analysis-gapfill/gapfill-/t=SmuSpoSraSreSveblchcoimmems,f=1149120,t=1152240	messages	ERROR		{}
lily-production-mainnet-analysis-gapfill/gapfill-/t=SmuSpoSraSreSveblchcoimmems,f=1149120,t=1152240	msapprovals	ERROR		{}
```

### Steps to Reproduce:

Run a gapfind/gapfill task which produces an error. (This is through normal operation of these tasks on mainnet using the tasks and ranges indicated above. LMK if I can help decipher the reporter name.)

**Comment by frrist** [comment]
This is basically a duplicate of https://github.com/filecoin-project/lily/issues/597. I suspect the underlying issue is that the error string is unable to be JSON marshaled when persisting the processing report to storage. It's probably worth pointing out that the GapFind and GapFill tasks reuse the indexer's logic and don't directly write to the visor_processing_reports table. 

Can you please add these findings to #597 and close this issue out?

**Comment by placer14** [comment]
[Migrated details](https://github.com/filecoin-project/lily/issues/597#issuecomment-934756410) and close as dupe.
