### ISSUE TITLE
Lily should attempt to backfill gaps in the database on startup

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#735]
### Description

When lily is brought down (say, at epoch `Edown`) and started up (say, at epoch `Eup` (for any reason: redeploy, maintenance, fault, etc), there is typically a gap between `[Edown,Eup)` while lily is not running. In order to ease handling of the service, we will automatically schedule gapfill/gapfind jobs on the `watch` task for all detected tasks over heights between `Edown`-1 and `Eup`+1 (offsets to ensure that (a) service interruption didn't also interrupt data persistence or (b) worry about race conditions around startup and epoch boundaries).

### Acceptance criteria

For each scheduled job:
- A. Automatically schedule gapfind proceeded (conditioned on gapfind success) by a gapfill
- B. Scheduled gapfill/gapfind jobs will only be applied to tasks included in the job
- C. Scheduled gapfill/gapfind jobs will only be applied to heights described by inspect the `visor_processing_reports` table to find the latest height which is `Edown`, and current HEAD which is `Eup`
- D. If the `visor_processing_reports` table is empty for that task, then gapfill/gapfind jobs will not be executed.
- E. An optional flag `--skip-auto-gapfill` can be included on the `watch` job CLI command which short-cricuits all above behavior (happy to make it an opt-out, but I think opt-in is the approach which does "the right thing" out of the box)

### Where to begin

- Create new job type (the job could be `gapfillfind`) which handles the state around waiting for gapfind to complete, checking results from gapfind, and conditionally starting gapfill. (This would also be valueable from a general ops perspective... there's aren't many cases where I would want to gapfind without gapfill.) (part of Req A)
- Expose this new job type within the CLI.
- Add auto gapfill logic to watch job.

**Comment by frrist** [comment]
An orchestrator of lily may choose to implement this logic, but I don't see it being a part of lily.
