### ISSUE TITLE
Migrate all lily's regular tables into hypertables

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#737]
### Description

In order to apply retention policies as provided by TimescaleDB, we will convert all of lily's non-hypertables into hypertables.

### Acceptance criteria

- All standard tables are converted to hypertables

### Where to begin

- Attempt to characterize operational overhead of applying the hypertable migration in order to inform/advise on deployment strategy
- Identify non-hypertables
- Create migration in lily which applies the updates which transform them

**Comment by frrist** [comment]
@placer14 are you handling this as a part of the on going work with timescale?

**Comment by placer14** [comment]
They aren't coupled together, but my work might (will probably) lead me toward solving this to achieve other side-effects (being able to apply retention policies over these tables). More concretely, it's a P1 sidequest in a sea of P0 work.

**Comment by frrist** [comment]
@placer14 is this still needed?

**Comment by placer14** [comment]
If we're moving away from Timescale as an infrastructure requirement, we should not be adopting hypertables. (This can still be an ETL concern. Just not managed by Lily migrations.) Closing.
