### ISSUE TITLE
Allow lily to extract specific models as a subset of a task.

### ISSUE THREAD

**Issue by kuchaguangjie** [filecoin-project/lily#762]
### Description

Currently lily will import data to postgresql by tasks, where each task may contain 1 or more tables.  
I know the tables of each task are probably related, but sometimes we don't need all the tables of a task.  

So, is there a plan to import by table, or provide flags to choose which tables to include / exclude for each task.  
If there is no such plan in near future, do you think it would  be possible to fork and impl that feature ?

**Refer:**

- https://filecoinproject.slack.com/archives/C0174P5M11T/p1635213514039000 _(discussion on slack)_

---
#### Example - `actorstatesminer` task

It contains **9** tables:

-    miner_current_deadline_infos
-    miner_fee_debts
-    miner_locked_funds
-    miner_infos
-    miner_sector_posts
-    miner_pre_commit_infos
-    miner_sector_infos
-    miner_sector_events
-    miner_sector_deals

But I only need **4** of them now:
* (3) miner_locked_funds
* (4) miner_sector_events
* (12) miner_sector_deals
* (13) miner_infos

### Where to begin
Maybe provide options to include/exclude tables of a task, and maybe default to all tables.

Thank you !

**Comment by frrist** [comment]
Hey @kuchaguangjie, yes this is doable -- and apologies for such a late response, this is a great idea. It will require a non-trivial amount of refracting in order to land. We will work to add this feature to a coming release.

How would you like this to behave from the cli? Would passing the models for extraction instead of the task names suffice? Example:
```bash
$ lily walk --tasks=miner_locked_funds,miner_sector_events,miner_sector_deals,miner_infos --from=100 --to=200
```

**Comment by kuchaguangjie** [comment]
@frrist Thanks, about the `cli` command, as long as it can specify in table level it's fine I guess.
You may split task into smaller tasks, or add another option to include / exclude table(s) as mentioned in initial post, or you may have even better ideas, while still keep the refactoring relatively easier.

**Comment by placer14** [comment]
@kuchaguangjie https://github.com/filecoin-project/lily/pull/871 🚀 ✨

**Comment by frrist** [comment]
via https://github.com/filecoin-project/lily/pull/869
