### ISSUE TITLE
gapfind vs consensus NULL_ROUND

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#767]
I'm seeing both `gap_find` and `consensus` reports showing NULL_ROUND and wonder the following:
- Are these NULL_ROUNDs equivalent?
- If so, can we converge their tasks to have the same?

Motivations
- Having different representations for the same thing is a smell.
- I don't think gap_find should touch both tables. It would be a better separation of concerns for consensus to just do that and let gapfind leave a hint in gap reports for the consensus task to check when/if it runs.

Aside: The only obvious difference is that `gap_find` does not have a state_root which would be valuable. So if we make gap_find say `consensus` instead, I'd want state_root to also be populated.

**Comment by iand** [comment]
By reports I assume you mean table?

What do you mean by converging the tasks? For clarity on terminology: 

 - `consensus` is a task used by a `walk` or `watch` job
 - `find` is a job that is used to find gaps that should be filled

If no `walk` or `watch` job has run the `consensus` task over a range of epochs then there will be missing data some of which may be null rounds. Therefore the `find` job needs to examine the chain across those missing epochs to determine whether each height should have data (a gap) or not (a null round).

Additionally, when the chain forks there may be different null rounds on each branch and a `watch` with low confidence could record either or both of these.

On that basis I think we need to keep gap finder's concept of null rounds distinct from consensus.

**Comment by iand** [comment]
A follow up thought. I question why gap finding writes to `visor_processing_reports` at all. It could write the null round information to `visor_gap_reports` instead.

**Comment by placer14** [comment]
My main concern is that gapfind can insert a single `NULL_ROUND` into processing reports with the task as `gap_find`. This is inconsistent with `gap_find`'s other behavior and creates a footgun in the representation of data in processing reports (having to require a special condition for the `gap_find` case is going to be surprising to other users not intimately aware that processing reports might have a job name (`gap find`) instead of only task names).

My preference would be that:
- gap find leaves a hint in the gap reports and
- tasks (regardless of gap/walk/watch job) produce `NULL_ROUND` rows in processing reports for themselves

**Comment by frrist** [comment]
via https://github.com/filecoin-project/lily/pull/884. This behavior is no longer present
