### ISSUE TITLE
lily job list data is stored in the database

### ISSUE THREAD

**Issue by LINJINTIANDE** [filecoin-project/lily#782]
### Description
There are too many tasks to be executed, which makes it difficult to distinguish clearly, which type of task each task belongs to, when to execute and end, and the information of releasing memory after each execution is gone. And to execute the script, it is difficult to judge whether the task is executed or not.
![image](https://user-images.githubusercontent.com/42436479/143539964-a8daf142-2d53-4a1a-93fd-34c8b3603c0c.png)

**Comment by iand** [comment]
I think this should be covered under #770. I'm going to close this issue but please add comments to #770 with the kinds of information you would like to have stored in database.
