### ISSUE TITLE
Lily does not successfully reopen existing repo on startup

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#796]
While deploying a new version of Lily (v0.8.4 -> v0.8.5) into our k8s cluster I found the node did not successfully resume syncing the chain from where it left off prior to deploy. When the pod came back up with the persistent volume containing the repo+datastore properly mounted, it seemed to ignore it completely and start syncing from current HEAD to epochs well into the past.

Badger logs don't show any errors. There are INFOs indicating 0 tables opening and replaying files from offsets at 0. This suggests badger found nothing to open? Unfortunately, in order to recover the service I destroyed the persistent volume so we can't inspect its state. I did not detect any problems in our logs with the volume being mounted by k8s.

Aside: I've seen this previously a few times, but wrote it off as a k8s scheduling problem. So maybe we can use this issue to start tracking more context around this failure.

**Comment by frrist** [comment]
Closing as there is insufficient data to debug this issue and I suspect this is more an issue of badger than lily
