### ISSUE TITLE
Support Snap Deal Miner Sector Events

### ISSUE THREAD

**Issue by frrist** [filecoin-project/lily#798]
### Description
With the addition of Snap Deals committed capacity upgrades will be deprecated: https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0019.md#deprecation-of-current-cc-upgrade. Lily will need modification to track any new events that arise from this.

### Acceptance criteria
- [x] Figure out what is changing: https://github.com/filecoin-project/lily/issues/798#issuecomment-1022593966
- [x] When its changing: the main network will go live with these changes sometime in late Feb or March
- [x] If it will be run on a testnet first (so we can test lily there): Yes it is on butterfly-SnapNet: https://status.filecoin.io/
- [x] Update lily: occurring here: https://github.com/filecoin-project/lily/pull/823

### Useful links:
https://github.com/filecoin-project/lotus/discussions/7898

**Comment by frrist** [comment]
Tracking issue in lotus https://github.com/filecoin-project/lotus/issues?q=is%3Aopen+is%3Aissue+label%3ASnapDeals

**Comment by frrist** [comment]
### What is changing?
[Deprecation of current CC Upgrade](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0019.md#deprecation-of-current-cc-upgrade): PreCommitSector will no longer be allowed to schedule current cc upgrades during prove commit. The data on chain tracking cc upgrades and the miner actor logic doing current cc upgrades will be removed. PreCommit message parameters will no longer include fields for specifying cc upgrades.

This means the following fields of the MinerPreCommitInfo model will always be null after the network upgrade:
https://github.com/filecoin-project/lily/blob/fe9a838028cb447ae54e8af0b5349d57c7912427/model/actors/miner/precommit.go#L30-L33
Note: we still need to keep them for chain processing before the upgrade. No action is required here.

----------------------

[Addition of the ProveReplicaUpdates Method on the Miner actor](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0019.md#provereplicaupdates-actor-method): a new message type once applied causes the `SectorOnChainInfo` struct to change for each `SectorOnChainInfo` in the message params (read the link for details of change)

This means:
- we can expect to see an uptick in the number of writes to the [`miner_sector_infos`](https://github.com/filecoin-project/lily/blob/fe9a838028cb447ae54e8af0b5349d57c7912427/model/actors/miner/sector.go#L15) table since it contains the states of all `SectorOnChainInfo` for each miner and those states will be changing when the sector is snapped.
- we may see an uptick of `SECTOR_EXTENDED` events as storage providers extend their sector expiration's so the sector is active long enough to contain deals with once it is "snapped".
- we need to change the way we diff `SectorOnChainInfo`s that have been modified since we only inspect the `Expiration` field: https://github.com/filecoin-project/lily/blob/9558021e284defe3dff4600dd68fcab34946ac7c/chain/actors/builtin/miner/diff.go#L213
    - The change will entail checking if the `SectorOnChainInfo.SectorKeyCID` has changed, and creating a `SECTOR_SNAPPED` event in the `miner_sector_events` table.

-----------------------

**Comment by frrist** [comment]
Also noting that `SectorKeyCID` can be null: https://github.com/filecoin-project/specs-actors/blob/v7.0.0-rc1/actors/builtin/miner/miner_state.go#L175, which means we need to be careful stringifying it else we'll get panics ☠️

**Comment by placer14** [comment]
> This means the following fields of the MinerPreCommitInfo model will always be null after the network upgrade:
lily/model/actors/miner/precommit.go

Is there a good reason we shouldn't just use the default values `(false, 0, 0, 0)`? If we do, we don't complicate our schema with another domain detail, no migration, we don't have to fix whatever queries touch that table, and future queries remain simpler. Plus, indicating that `IsReplaceCapacity = false` (and always will be) keeps the data honest as well.

**Comment by frrist** [comment]
And we'll need to keep these around for historic reasons too, all states prior to the upgrade can set these fields.

**Comment by frrist** [comment]
closed via #823
