### ISSUE TITLE
Running the message task visor_processing_reports reports different errors. I don’t know why I can explain it.

### ISSUE THREAD

**Issue by LINJINTIANDE** [filecoin-project/lily#800]
### Description
Running the message task visor_processing_reports reports different errors. I don’t know why I can explain it.
![image](https://user-images.githubusercontent.com/42436479/146120459-5cf22599-f900-4169-907d-dfcc459dd266.png)
![image](https://user-images.githubusercontent.com/42436479/146120469-967090d6-8dc2-45c1-af0f-526d03875a64.png)

**Comment by frrist** [comment]
What version of lily are you running?

**Comment by LINJINTIANDE** [comment]
@frrist v0.8.5

**Comment by LINJINTIANDE** [comment]
@frrist v0.8.5

**Comment by frrist** [comment]
via https://github.com/filecoin-project/lily/pull/799
