### ISSUE TITLE
Story: Lily should track Fault and Termination fees

### ISSUE THREAD

**Issue by hsanjuan** [filecoin-project/lily#801]
### Description

There is currently no way of tracking fault and termination fee-events. The only way right now is to take the sum of gas burnt by messages, compare that with how f099 balance, and assume that the mismatch comes from fault and termination fees.

These fees are not explicit on chain and happen internally. For example, there is a fee on declare fault. There are fees when sectors transition to FAULTED, but on the 2nd day and onwards (I think they can recovered without penalty in the first 24h of fault).

### Acceptance criteria

Fault/termination fee events are different from sector_events (a fault event not always triggers a fault fee event, and a fault fee event happens several times per sector fault).

Thus, I would like a table that tracks internal sends to f099 and that allows to track these events.

Unknowns to make informed decisions on:

* I don't know how many types of event are burning funds. Potentially there could be non-sector related events (perhaps market-related). Ideally, we would have a table for all of them but,
* Ideally, the table would allow me to list all the fault-fees/termination fees paid by a miner/sector pair. However, having that is probably incompatible with having a table for all types of fees, if there are several types of fees.

### Where to begin

* Start figuring out what sends money to f099 that is not part of derived_gas_outputs already, decide on table/tables to be able to track that. Focus on delivering at least fault and termination fees tracking.

**Comment by frrist** [comment]
The miner actor uses the method [`burnFunds`](https://github.com/filecoin-project/specs-actors/blob/dde869a7cdf2e5060ab75f2a3a74fa399f7b6875/actors/builtin/miner/miner_actor.go#L2664-L2670) to pay/burn fees/penalties to the [`BurntFundsActorAddr`](https://github.com/filecoin-project/specs-actors/blob/6d78706df9ab9d6210a73596280e97bef0541eb4/actors/builtin/singletons.go#L18).

The `burnFunds` method is called in a variety of places:
- [`DisputeWindowedPoSt`](https://github.com/filecoin-project/specs-actors/blob/dde869a7cdf2e5060ab75f2a3a74fa399f7b6875/actors/builtin/miner/miner_actor.go#L628)

- [`PreCommitSectorBatch`](https://github.com/filecoin-project/specs-actors/blob/dde869a7cdf2e5060ab75f2a3a74fa399f7b6875/actors/builtin/miner/miner_actor.go#L854)

- [`ProveCommitAggregate`](https://github.com/filecoin-project/specs-actors/blob/dde869a7cdf2e5060ab75f2a3a74fa399f7b6875/actors/builtin/miner/miner_actor.go#L984)

- [`DeclareFaultsRecovered`](https://github.com/filecoin-project/specs-actors/blob/dde869a7cdf2e5060ab75f2a3a74fa399f7b6875/actors/builtin/miner/miner_actor.go#L1745)

- [`ApplyRewards`](https://github.com/filecoin-project/specs-actors/blob/dde869a7cdf2e5060ab75f2a3a74fa399f7b6875/actors/builtin/miner/miner_actor.go#L1910)

- [`ReportConsensusFault`](https://github.com/filecoin-project/specs-actors/blob/dde869a7cdf2e5060ab75f2a3a74fa399f7b6875/actors/builtin/miner/miner_actor.go#L1991)

- [`WithdrawBalance`](https://github.com/filecoin-project/specs-actors/blob/dde869a7cdf2e5060ab75f2a3a74fa399f7b6875/actors/builtin/miner/miner_actor.go#L2061)

- [`RepayDebt`](https://github.com/filecoin-project/specs-actors/blob/dde869a7cdf2e5060ab75f2a3a74fa399f7b6875/actors/builtin/miner/miner_actor.go#L2086)

- [`processEarlyTerminations`](https://github.com/filecoin-project/specs-actors/blob/dde869a7cdf2e5060ab75f2a3a74fa399f7b6875/actors/builtin/miner/miner_actor.go#L2215)
    - Invoked via [`TerminateSectors`](https://github.com/filecoin-project/specs-actors/blob/dde869a7cdf2e5060ab75f2a3a74fa399f7b6875/actors/builtin/miner/miner_actor.go#L1490)
    - Invoked at the end of the last epoch for each proving deadline and triggered by the Cron actor via miner method [`OnDeferredCronEvent`](https://github.com/filecoin-project/specs-actors/blob/dde869a7cdf2e5060ab75f2a3a74fa399f7b6875/actors/builtin/miner/miner_actor.go#L2109)
    
Fees/penalties paid by a miner can be tracked by inspecting internal messages that result from a call to the exported methods listed above. Note that the internal message table already tracks the [top-level message](https://github.com/filecoin-project/lily/blob/master/model/messages/internal.go#L21) that triggers internal messages, and once https://github.com/filecoin-project/lily/pull/795 lands these internal sends will be tracked.

**Comment by frrist** [comment]
blocked on https://github.com/filecoin-project/lily/issues/865

**Comment by frrist** [comment]
via https://github.com/filecoin-project/lily/pull/1027
