### ISSUE TITLE
lily watch or walk starts the message task, the database gets the next height data

### ISSUE THREAD

**Issue by LINJINTIANDE** [filecoin-project/lily#804]
lily watch or walk start the message task, the database table: block_messages,, messages, messages_gas_economy, receipts,. The data pulled is the data of the next height, not the data of the current height. I don't know if it was done intentionally or for some reason.

https://github.com/filecoin-project/lily/blob/6a0eb342e01dcb59e63db14b3eb22a8857102536/lens/util/repo.go#L178
https://github.com/filecoin-project/lily/blob/6a0eb342e01dcb59e63db14b3eb22a8857102536/lens/util/repo.go#L179
https://github.com/filecoin-project/lily/blob/6a0eb342e01dcb59e63db14b3eb22a8857102536/tasks/messages/message.go#L185
https://github.com/filecoin-project/lily/blob/6a0eb342e01dcb59e63db14b3eb22a8857102536/tasks/messages/message.go#L187
![image](https://user-images.githubusercontent.com/42436479/147630939-08b0792b-1d12-480e-8c3e-279508436a19.png)
![image](https://user-images.githubusercontent.com/42436479/147634727-5e6d9041-a5d6-478f-8ce0-eafc34047fd3.png)

**Comment by frrist** [comment]
via https://github.com/filecoin-project/lily/pull/869
