### ISSUE TITLE
Values passed --tasks should be validated

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#808]
When passing an argument to --tasks, I would expect it to be checked against the existing list of tasks and exit with an error if a task provided is not actually a task. This is to avoid starting a job where I have a typo or have misremembered the task name. Better to know when I start than when I go to check the results after everything is done. This is especially problematic when you especially don't want the default behavior of running all the tasks.

**Comment by frrist** [comment]
What command did you run that failed to validate tasks? 
They seem to validate for the below:
```
$ lily_mainnet walk -tasks=not_a_task --from 100 --to 100
unknown task: not_a_task

$ lily_mainnet watch -tasks=not_a_task
unknown task: not_a_task
```

**Comment by frrist** [comment]
via https://github.com/filecoin-project/lily/issues/818
