### ISSUE TITLE
gap find --tasks is ignored

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#809]
I attempted to run a gap find for a specific task on an epoch which no tasks have been completed for. Gapfind seems to ignore which tasks I want it limited to and instead runs them for all. This is not really a big issue for gapfind as it's a very lightweight task, but might surprise a user who is not expecting it.

**Comment by frrist** [comment]
Without the details of the commands given, this will be challenging to debug. Could you please expand this with details on the command you ran?

**Comment by placer14** [comment]
Sure. For example, executing `gap find --tasks messages --to 100 --from 100` you would see GAPs reported for all tasks at epoch 100. I would have expected to only see a GAP report for the `messages` task.

**Comment by frrist** [comment]
via https://github.com/filecoin-project/lily/pull/884
