### ISSUE TITLE
Idea: Include column in processing and gap reports for soft delete 

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#817]
When troubleshooting and exploring lily task behavior, sometimes the state of processing and gap tables are relevant to the test case. This means that records must be edited or deleted to make lily do the desired behavior. In order to preserve prior reports, it would be useful to have a soft delete column (`is_deleted` or similar) which lily will use to ignore certain rows when referring to the tables' state. This column would default to false and can be manually changed to suit the needs of the developer/operator while preserving those reports for later analysis.

**Comment by frrist** [comment]
This will add complexity to an already complex process, a few alternatives that come to mind:
1. Export the portion of the table you are manually testing to a CSV file. restore the CSV when the test is complete.
2. Write a unit test in the gap find testing suite.
3. Use a temporary database with data imported from the main database.
