### ISSUE TITLE
Message Parse Param Changes

### ISSUE THREAD

**Issue by frrist** [filecoin-project/lily#819]
### Description
With https://github.com/filecoin-project/lily/pull/799 landed the values of the parsed_messages params row have changed slightly. Here are few examples of the changes:
| Method Name | Previous | Current |
|---------------|----------|---------|
| Propose | {"To": "f1gojwyi2jcvptacdaopoh6as2whvwv2i67j2gqbq", "Value": "3149869747391647641", "Method": 0, "Params": ""} | {"To": "f1gojwyi2jcvptacdaopoh6as2whvwv2i67j2gqbq", "Value": "3149869747391647641", "Method": 0, "Params": null} |
| TerminatedSectors | {"Terminations": [{"Sectors": {"rle": "[14184,1]", "_type": "bitfield", "elemcount": "1"}, "Deadline": 6, "Partition": 0}]} | {"Terminations": [{"Sectors": [14184, 1], "Deadline": 6, "Partition": 0}]} |
| ProveCommitSectors | {"Proof": "<omitted_for_clarity>", "SectorNumber": 287854} | {"Proof": "<omitted_for_clarity>", "SectorNumber": 287854}|
| SubmitWindowedPost | {"Proofs": [{"PoStProof": 9, "ProofBytes": "s6R286ikYpAIu9trmrrYghMIs0qRgMcazPnur25XoGkvT+a6eQzb70bGdpovFBBisetEzoWBNEx3lwFSeTbkfVxhNP+JyyddqMUzrle0jDj+xLy7EfunGt1OumWV2TCWATHtgup43Za7LecSQg1fHW1VQpu4hynobXsvRNSrIUPXuHR5BXJUsGRn1zfrFV4Jj6Te5tJ5V3UldfUOu74Z7+3PxQeUKyzqubGxNXITxboCKNds3Q3ocOdI4T3AkyqK"}], "Deadline": 35, "Partitions": [{"Index": 0, "Skipped": {"rle": "[0]", "_type": "bitfield", "elemcount": "0"}}], "ChainCommitRand": "h1MbWURLsVmZB2FSyb4Ff5iGjsyJRpfA7UWfdOTrsg4=", "ChainCommitEpoch": 1480063} | {"Proofs": [{"PoStProof": 9, "ProofBytes": "s6R286ikYpAIu9trmrrYghMIs0qRgMcazPnur25XoGkvT+a6eQzb70bGdpovFBBisetEzoWBNEx3lwFSeTbkfVxhNP+JyyddqMUzrle0jDj+xLy7EfunGt1OumWV2TCWATHtgup43Za7LecSQg1fHW1VQpu4hynobXsvRNSrIUPXuHR5BXJUsGRn1zfrFV4Jj6Te5tJ5V3UldfUOu74Z7+3PxQeUKyzqubGxNXITxboCKNds3Q3ocOdI4T3AkyqK"}], "Deadline": 35, "Partitions": [{"Index": 0, "Skipped": [0]}], "ChainCommitRand": "h1MbWURLsVmZB2FSyb4Ff5iGjsyJRpfA7UWfdOTrsg4=", "ChainCommitEpoch": 1480063} |
| Propose | {"To": "f1em4vxj6ch7ktjqzn2bm5l6mhbfblhuzqhpvzh5y", "Value": "161000000000000000000", "Method": 0, "Params": ""} | {"To": "f1em4vxj6ch7ktjqzn2bm5l6mhbfblhuzqhpvzh5y", "Value": "161000000000000000000", "Method": 0, "Params": null} |
| PreCommitSectorBatch | {"Sectors": [{"DealIDs": [], "SealProof": 8, "SealedCID": {"/": "bagboea4b5abcasvz2vj6ftxpdjkkrt4lhh36gqcdrohemdxtjnx2efkm6sfgxptr"}, "Expiration": 3029491, "SectorNumber": 70630, "SealRandEpoch": 1478430, "ReplaceCapacity": false, "ReplaceSectorNumber": 0, "ReplaceSectorDeadline": 0, "ReplaceSectorPartition": 0}]} | {"Sectors": [{"DealIDs": null, "SealProof": 8, "SealedCID": {"/": "bagboea4b5abcasvz2vj6ftxpdjkkrt4lhh36gqcdrohemdxtjnx2efkm6sfgxptr"}, "Expiration": 3029491, "SectorNumber": 70630, "SealRandEpoch": 1478430, "ReplaceCapacity": false, "ReplaceSectorNumber": 0, "ReplaceSectorDeadline": 0, "ReplaceSectorPartition": 0}]} |
| DeclareFaultRecovered | {"Recoveries": [{"Sectors": {"rle": "[10816,31,1407,1,2,23,1,4,1,1,1405,1,3,26,1,1,1,1,521,1,3,915,58,1,2,1343]", "_type": "bitfield", "elemcount": "2349"}, "Deadline": 6, "Partition": 0}]} | {"Recoveries": [{"Sectors": [10816, 31, 1407, 1, 2, 23, 1, 4, 1, 1, 1405, 1, 3, 26, 1, 1, 1, 1, 521, 1, 3, 915, 58, 1, 2, 1343], "Deadline": 6, "Partition": 0}]}|

Specifically, I'd like to call out the `DeclareFaultsRecovered` messages as the field `elemcount` containing the number of bits set in the corresponding bitfield is no longer accessible. (Note: this effects all message parsing with params containing Bitfields)

Old:
```{"Recoveries": [{"Sectors": {"rle": "[10816,31,1407,1,2,23,1,4,1,1,1405,1,3,26,1,1,1,1,521,1,3,915,58,1,2,1343]", "_type": "bitfield", "elemcount": "2349"}, "Deadline": 6, "Partition": 0}]}```

Current: 
```{"Recoveries": [{"Sectors": [10816, 31, 1407, 1, 2, 23, 1, 4, 1, 1, 1405, 1, 3, 26, 1, 1, 1, 1, 521, 1, 3, 915, 58, 1, 2, 1343], "Deadline": 6, "Partition": 0}]}|```

Previously we stated this field was needed in https://github.com/filecoin-project/lily/issues/569, I suspect this continues to hold true. Prior to #799 this field was parsed using some custom code added to what we ported from statediff https://github.com/filecoin-project/lily/pull/573. 

### Problem
We no longer have access to the pre-computed count indicating the number of sectors present in messages with params of the bitfield type.

Solutions I have tried to remedy this with:
- Continue using [Statediff](https://github.com/filecoin-project/statediff): This library is no longer being maintained, if we want to use it will need to support it ourselves. 
- [Modify the go-bitfield json marshaller to do what we need](https://github.com/filecoin-project/go-bitfield/pull/58): Library maintainers are very reluctant to accept this change as it breaks the lotus API. 
- [Implement an IPLD schema for the Filecoin types](https://github.com/ipld/ipld/blob/master/_legacy/specs/data-structures/filecoin/chain.md): This isn't maintained or completed past actors v2, we are approaching v7. 
- Calculate the count in SQL (its a trivial function to write): This likely isn't performant enough.
- Write a custom json marshaller for structs containing bitfields: This is non-trivial to do and would prefer to take this route as a last resort.

**Comment by hsanjuan** [comment]
I'd suggest you fork/branch go-bitfield with the change you need and import that version into Lily for the unmarshaling. This library is pretty stable (no changes since 1 year ago) and maintenance overhead would be very small or none. I don't see any issues with doing this.

The SQL count function is useful to have too, but we should maintain our data format (which includes `elemcount` and which is very practical).

**Comment by frrist** [comment]
Unfortunately forking won't work due to lotus and specs-actors library methods expecting the type `filecoin-project/go-bitfield` rather than `frrist/go-bitfield`.

Using a custom branch from go-bitfield works, but feels a bit fragile, I have done this here: https://github.com/filecoin-project/lily/pull/820

Alternatively I have written a wrapper that allow for any types Json marshaller to be overloaded with our own here: https://github.com/filecoin-project/lily/pull/821
