### ISSUE TITLE
Gap Reports table falls into a GAP && FILLED state for a task/epoch and can't resolve

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#852]
### Describe the bug:

Somehow, the database can get into the state where a specific task and height will have two records; one with GAP and one with FILLED. Because:

1. we have an primary key index on height, task, and status and 
2. because of the way we manage that table during find/fill operations

When a fill task attempts to resolve the GAP record by changing it to the FILLED status, the index rejects the change. And fill will create as many additional processing reports as you run fill over that task and epoch.

### Steps to Reproduce:

It's unclear how one might get into the state where a task/height is both FILLED and GAP. But creating the following would suffice:

```yaml
- height: 1
  task: blocks
  status: GAP
- height: 1
  task: blocks
  status: FILLED
```

And attempt to run fill over that epoch.

**Comment by frrist** [comment]
via https://github.com/filecoin-project/lily/pull/884
