### ISSUE TITLE
Generate FVM actor API from IPLD schema

### ISSUE THREAD

**Issue by frrist** [filecoin-project/lily#859]
### Description
Currently, Lily generates an [Actor API (shim)](https://github.com/filecoin-project/lily/tree/master/chain/actors/builtin#actors) from the specs-actors implementation to abstract access over the different Filecoin actor versions; using the API to perform actor state extraction. With the addition of FVM and rust-based actors, this pattern will become infeasible over time as development and feature focus shifts from specs-actors to the rust actors.

One way for Lily to continue generating this Actor API is through the use of an IPLD schema. An example of such schema may be found here: https://github.com/ipld/ipld/blob/master/_legacy/specs/data-structures/filecoin. There are a couple of different libraries that may be used to generate an API from said schema:
- [bindnode](https://github.com/ipld/go-ipld-prime/tree/master/node/bindnode): reflection-based, looks very easy to use and maintain, might not be the most performant route.
- [gengo](https://github.com/ipld/go-ipld-prime/tree/master/schema/gen/go): codegen-based, less easy to use and maintain, incomplete, likely more performant than bindnode.

While gengo is worth keeping an eye on the owner of this issue should start with bindnode since it appears to be the more mature offering.

As far as writing the IPLD schema is concerned there are a few things to consider:
1. Do we need a schema for each actor version?
    - Probably not, the API we have now works and back-porting a schema for all previous actor versions will be very time-consuming with little to gain.
1. Where does the schema live and who maintains it?
    - For now, this can just go in Lily, but eventually, it could be moved elsewhere for consumption by other projects -- lotus uses a similar pattern for its actor API (in fact that's where Lily got its current implementation)
1. How do we start writing the schema, isn't that a load of typing?
    - Yeah, seems that way. I think specs-actors v7 could be a good place to start. Perhaps a schema could be generated from the code there, really not sure.

### Acceptance criteria
- [ ] Implement an IPLD schema for actors v7 based on the structures found in specs-actors.
- [ ] Generate an API from the schema using bindnode.
- [ ] Replace the current Actor API with IPLD-scheme one, call appropriate API based on actor versions.

**Comment by placer14** [comment]
It seems whatever the direction (reflection vs codegen), the IPLD schema will be a blocker. How would one begin that journey? (Where to start and any process/pattern insights you can provide.)

((Also, bounty?!))

**Comment by frrist** [comment]
This isn't a blocker (I'll change the priority of the issue to better reflect this), since we are making do without it at the moment, but it would be _really_ nice to have. 

The process and pattern are outlined in the OP: there is an example of an existing schema, as well as the tools needed to generate code from the schema. See point 3 and the acceptance criteria for getting started. This is a fairly open ended problem, and more thought and cross team coordination.

**Comment by frrist** [comment]
Tracked via: https://github.com/filecoin-project/builtin-actors/issues/194
