### ISSUE TITLE
Track when a re-org happens, its length and any other information

### ISSUE THREAD

**Issue by frrist** [filecoin-project/lily#863]
- What height it happened on
- Heaviest tipset
- How deep (what height it branched off)
- Branching tipset

**Comment by hsanjuan** [comment]
Related: https://github.com/filecoin-project/lily/issues/831

**Comment by frrist** [comment]
This information can be derived from the [chain_consensus model](https://github.com/filecoin-project/lily/blob/v0.11.0/model/chain/consensus.go#L14-L19) if lily is run with a confidence of 1.
