### ISSUE TITLE
Lily's watch should tolerate re-orgs

### ISSUE THREAD

**Issue by frrist** [filecoin-project/lily#864]
- A re-org does not cause errors and is considered business as usual during walks.
- Processing on the forked branch continues until the re-org happens.
- Processing on the heaviest branch after re-org continues from the place where the fork branched off (no missing data for heaviest branch).

**Comment by hsanjuan** [comment]
Blocked waiting indexer refactor, horizontal scalability.

**Comment by frrist** [comment]
Closed via: https://github.com/filecoin-project/lily/pull/869. The watcher is now stateless and tolerant of reorgs.
