### ISSUE TITLE
lily migrate 1.4 upgrade to 1.5 cannot create super table

### ISSUE THREAD

**Issue by LINJINTIANDE** [filecoin-project/lily#889]
Try the pg version: 2.5.0-pg13 and 2.4.1-pg13, the 1.4 version upgrades the 1.5 version, and the following error is reported. 
`2022-03-06T00:27:27.084+0800    INFO    lily/commands   commands/setup.go:71    Visor version:v0.8.6+dirty
2022-03-06T00:27:27.134+0800    INFO    lily/storage    storage/migrate.go:187  current database schema is version 1.4
2022-03-06T00:27:27.137+0800    INFO    lily/storage    storage/migrate.go:260  running schema migration from version 1.4 to version 1.5
run migration: ERROR #42883 function create_hypertable(unknown, unknown, chunk_time_interval => integer, if_not_exists => boolean) does not exist
`
### Lily Version: v0.86

----

The cause and solution for the fix is describe at https://github.com/filecoin-project/lily/issues/889#issuecomment-1112399767

## TODO

- [ ] Update migrations to include schema as part of `create_hypertable` calls.
- [ ] Check if there are other indicies, function creations or other objects which require the same

```sql
  SELECT create_hypertable(
    'miner_sector_infos_v7',
    'height',
    chunk_time_interval => 20160,
    if_not_exists => TRUE
  );
```

should be 

```sql
  SELECT {{ .SchemaName | default "public"}}.create_hypertable(
    'miner_sector_infos_v7',
    'height',
    chunk_time_interval => 20160,
    if_not_exists => TRUE
  );
```

Example from https://github.com/filecoin-project/lily/blob/master/schemas/v1/5_miner_sector_snaps.go#L36

**Comment by frrist** [comment]
Cc @placer14 I think you hit this as well?

**Comment by placer14** [comment]
Yes, I did. I didn't have time to troubleshoot this (and got distracted and forgot to report, so thank you @LINJINTIANDE 🙏). Curiously, I could log into the database with the same user I attempted to migrate with and could manually run the migration statements successfully. Further, I attempted to add schema in the `create_hypertable` call within the migration to make resolving the function more specific and that did not change anything. I also attempted to run the migrate subcommand using a DB admin user which resulted in the same error.

 can only think that the migration has some sort of non-obvious transformation that's happening here. There is nothing I can see that's obviously wrong with the SQL and it looks mostly like a copy from prior migrations (which is fine). This confuses me a bit. 

Inspecting this from the lily side is painful. There are no hooks to do a "dry-run" of a migration where the SQL gets spit out without committing the changes. The ORM/migration lib also doesn't (obviously) allow a way to split the formatted/interpolated/sql-escaped output before sending to the server. This is about where I stopped troubleshooting and just manually applied the migrations.

**Comment by frrist** [comment]
I've hit this error while running lily against timescale cloud. I was able to fix it by installing the timescale extensions on the database (this came as a bit of a surprise to me...).  @LINJINTIANDE what database were you using when you hit this?

**Comment by LINJINTIANDE** [comment]
@frrist postgres running with docker-compose provided by the lily project,The way I solved it was to manually run the code upgrade
version:2.4.1-pg13

**Comment by placer14** [comment]
@LINJINTIANDE here's the problem, your `search_path` for that user is not resolving to the schema which contains the `create_hypertable` method. The solution is to update the existing migrations to specify the schema name as part of the method call.

Will update the details on this issue to track the fix.
