### ISSUE TITLE
lily runs without error against old schema versions

### ISSUE THREAD

**Issue by frrist** [filecoin-project/lily#909]
### Describe the bug:
Lily will run and fail to persist data against schemas older than its configured version:
https://github.com/filecoin-project/lily/blob/d0cf5cc7cc404f10ed525912465f1618e57a3851/storage/migrate.go#L138-L150

### Steps to Reproduce:
from the lily repo on master:
1. `make dockerdown && make dockerup` (initialize a fresh database)
2. `make` (build the thing)
3. `./lily migrate --latest --db="postgres://postgres:password@localhost:5432/postgres?sslmode=disable" --to=1.4` (initialize to a less than most recent (1.5) version)
4. `./lily walk --from=0 --to=1000 --tasks=actorstatesminer`
5. observe the error:
```json
{
  "level": "error",
  "ts": "2022-03-10T00:35:07.689Z",
  "logger": "lily/chain",
  "caller": "chain/indexer.go:506",
  "msg": "persistence failed",
  "current": 1618863,
  "next": 1618864,
  "task": "actorstatesminer",
  "error": "persisting model: ERROR #42P01 relation \"miner_sector_infos_v7\" does not exist",
  "errorVerbose": "persisting model:\n    github.com/filecoin-project/lily/storage.(*TxStorage).PersistModel\n        /go/src/github.com/filecoin-project/lily/storage/sql.go:428\n  - ERROR #42P01 relation \"miner_sector_infos_v7\" does not exist"
}
```
This is due to lily expecting schema version 1.5, but accepting 1.4 at runtime.

**Comment by placer14** [comment]
FYI, this created some migration issues on the previous deployment. In the past, I was able to run two versions in tandem against the DB so that I can migrate without interrupting either process from writing to the DB.

I think the old behavior is not a big deal considering all of our schema migrations are additive to-date. It's not a huge deal as it only creates a little downtime, but it would make automation much easier the way the behavior worked prior to this fix.

Please close again if you feel strongly against.

**Comment by frrist** [comment]
The old behavior caused the persistence of models not yet defined in the schema to fail (as mentioned in the OP). 
With the goal of running two different versions of lily against the same database, we could allow lily to run against a database with a schema newer than lily's current version, but not older. 
How does that sound?

**Comment by placer14** [comment]
What if persistence failures generate an ERROR processing report and continue until the schema is migrated. That would also make it super obvious why the instance hasn't started working (which is what confused me).

**Comment by frrist** [comment]
Unfortunately, that's not really in the spirit of _processing_ reports, and complicated from an implementation perspective s lily would need to be aware of _why_ persistence is failing. e.g. if it can't connect to the database then writing a report stating this isn't possible.

Allowing Lily to run against schemas that are newer than its current, since schemas are additive, looks to be the simplest solution here.
