### ISSUE TITLE
Fix archive data bugs fix in Lily v0.8.8

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#911]
### Describe the bug:

There was missing and incorrect data and the following epochs/tasks require a re-run using Lily v0.8.8:

- `messages` task (targeting malformed data in `parsed_messages`) from epoch `1594679` to current
- `actorstatesminer` task (targeting missing data in `miner_sector_events`) from epoch `1594679` to current

**Comment by iand** [comment]
Need to create a partial or full lily snapshot to cover this range (highest we have is 1593203)

**Comment by iand** [comment]
Completed and copied files to fil-archive. Nightly sync will push these to s3 tonight.
