### ISSUE TITLE
Analysis `miner_sector_events` CSV job halted

### ISSUE THREAD

**Issue by yaoluoye** [filecoin-project/lily#934]
We need the miner_sector_events dump files to fill up our DB, but the latest file is "miner_sector_events-2022-03-21.csv.gz", is a plan to upload the newer dump files?

**Comment by placer14** [comment]
Thanks for the report. This is supposed to be an automated daily job. I'll investigate and see that we include some alerts for when things break. 🤝

**Comment by kasteph** [comment]
The Lily node for walking the task that exports this CSV stopped running. I've restarted the job.

It will process the day's export one finality after midnight. I will check back in here once again tomorrow or in two days for more updates.

Thank you for letting us know! 🙏🏽

**Comment by kasteph** [comment]
Update: The archiving process looks like it's going well at the moment -- it will take some time to catch up though because it's doing archiving of some heavy tasks (miner, market, messages). I'll keep posting updates here.

**Comment by kasteph** [comment]
`miner_sector_events` has now caught up to 2022-04-28. The last two weeks' worth of CSV files will be processed next week. Thank you for your patience 🙇🏽
