### ISSUE TITLE
[DOCS] Broken links to task definition 

### ISSUE THREAD

**Issue by frrist** [filecoin-project/lily#942]
### Describe the bug:
Model links in table: https://lilium.sh/software/lily/operation/#tasks are broken

### Steps to Reproduce:
click: https://lilium.sh/software/lily/operation/models.md#block_headers

**Comment by kasteph** [comment]
I think the schema for the URL should be https://lilium.sh/data/models/#actor_states

**Comment by kasteph** [comment]
fixed by https://github.com/filecoin-project/sentinel/commit/b15409d139d87c901e6894d375a4638bdca00b85

**Comment by hsanjuan** [comment]
sorry, some paths changed on the migration.
