### ISSUE TITLE
Some tasks have inconsistent start times in processing report

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#945]
Reviewing task report data, I noticed that some tasks seem to start 30s before other tasks for the same height. See this gist which has reports from three different instances across multiple tasks.

https://gist.github.com/placer14/a18ef7a2cddc67d2f07e2e4b2658cb87

This screenshot should make it easier to see the difference:
<img width="889" alt="image" src="https://user-images.githubusercontent.com/305332/165523717-fdc9ae51-6894-41a7-8b10-18e28d870d53.png">

using Lily v0.9.0

**Comment by frrist** [comment]
The tasks with different start times are coming from different reporters (read jobs), so having different start times isn't unusual. Here are some code pointer to where start times are recorded and added to the reports (feel free to close this issue out if you agree with assertions made here):
https://github.com/filecoin-project/lily/blob/da4a88a3f6d79543cea8c3255c8c81bbe3dae2c9/chain/indexer/processor/state.go#L100-L103
https://github.com/filecoin-project/lily/blob/da4a88a3f6d79543cea8c3255c8c81bbe3dae2c9/chain/indexer/processor/state.go#L147-L150
https://github.com/filecoin-project/lily/blob/da4a88a3f6d79543cea8c3255c8c81bbe3dae2c9/chain/indexer/processor/state.go#L195-L198
https://github.com/filecoin-project/lily/blob/da4a88a3f6d79543cea8c3255c8c81bbe3dae2c9/chain/indexer/processor/state.go#L243-L258

**lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=60s,t=Sma**
| height | reporter | task | started\_at | completed\_at | state\_root | status | status\_information | errors\_detected |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=60s,t=Sma, | builtin | 2022-04-27 12:53:30.514443 +00:00 | 2022-04-27 12:53:30.514472 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=60s,t=Sma, | market\_deal\_state | 2022-04-27 12:53:30.514454 +00:00 | 2022-04-27 12:53:31.762955 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=60s,t=Sma, | market\_deal\_proposal | 2022-04-27 12:53:30.514454 +00:00 | 2022-04-27 12:53:31.895775 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |

**lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems,**
| height | reporter | task | started\_at | completed\_at | state\_root | status | status\_information | errors\_detected |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | receipt | 2022-04-27 12:54:00.544814 +00:00 | 2022-04-27 12:54:06.338470 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | block\_message | 2022-04-27 12:54:00.544814 +00:00 | 2022-04-27 12:54:06.355485 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | block\_parent | 2022-04-27 12:54:00.544811 +00:00 | 2022-04-27 12:54:00.545213 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | builtin | 2022-04-27 12:54:00.544809 +00:00 | 2022-04-27 12:54:00.544961 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | chain\_consensus | 2022-04-27 12:54:00.544811 +00:00 | 2022-04-27 12:54:00.544927 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | chain\_economics | 2022-04-27 12:54:00.544811 +00:00 | 2022-04-27 12:54:00.545552 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | chain\_power | 2022-04-27 12:54:00.544946 +00:00 | 2022-04-27 12:54:01.361709 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | chain\_reward | 2022-04-27 12:54:00.544946 +00:00 | 2022-04-27 12:54:01.361524 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | derived\_gas\_outputs | 2022-04-27 12:54:00.544814 +00:00 | 2022-04-27 12:54:06.341155 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | drand\_block\_entrie | 2022-04-27 12:54:00.544811 +00:00 | 2022-04-27 12:54:00.545001 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | internal\_messages | 2022-04-27 12:54:00.544814 +00:00 | 2022-04-27 12:54:07.246012 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | internal\_parsed\_messages | 2022-04-27 12:54:00.544814 +00:00 | 2022-04-27 12:54:07.246043 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | message | 2022-04-27 12:54:00.544814 +00:00 | 2022-04-27 12:54:06.351258 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | message\_gas\_economy | 2022-04-27 12:54:00.544814 +00:00 | 2022-04-27 12:54:06.338183 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | multisig\_approvals | 2022-04-27 12:54:00.544814 +00:00 | 2022-04-27 12:54:06.338108 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | multisig\_transaction | 2022-04-27 12:54:00.544946 +00:00 | 2022-04-27 12:54:01.361445 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | power\_actor\_claim | 2022-04-27 12:54:00.544946 +00:00 | 2022-04-27 12:54:01.611556 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | verified\_registry\_verified\_client | 2022-04-27 12:54:00.544946 +00:00 | 2022-04-27 12:54:01.361533 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | verified\_registry\_verifier | 2022-04-27 12:54:00.544946 +00:00 | 2022-04-27 12:54:01.361455 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | actor | 2022-04-27 12:54:00.544946 +00:00 | 2022-04-27 12:54:01.375793 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | actor\_state | 2022-04-27 12:54:00.544946 +00:00 | 2022-04-27 12:54:01.393800 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=SmuSpoSraSreSveblchcoimmems, | block\_header | 2022-04-27 12:54:00.544811 +00:00 | 2022-04-27 12:54:00.545076 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |

**lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=Sin,**
| height | reporter | task | started\_at | completed\_at | state\_root | status | status\_information | errors\_detected |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=Sin, | id\_address | 2022-04-27 12:53:30.514382 +00:00 | 2022-04-27 12:53:31.270559 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-v3-prime/watch-9lUJaO/s=db,c=100,w=30s,t=Sin, | builtin | 2022-04-27 12:53:30.514360 +00:00 | 2022-04-27 12:53:30.514408 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |

**lily-production-mainnet-analysis-migrationtemp-prime/watch-wD4lAH/s=db,c=100,w=60s,t=Sma,**
| height | reporter | task | started\_at | completed\_at | state\_root | status | status\_information | errors\_detected |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1758486 | lily-production-mainnet-analysis-migrationtemp-prime/watch-wD4lAH/s=db,c=100,w=60s,t=Sma, | builtin | 2022-04-27 12:53:30.497486 +00:00 | 2022-04-27 12:53:30.497550 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-migrationtemp-prime/watch-wD4lAH/s=db,c=100,w=60s,t=Sma, | market\_deal\_proposal | 2022-04-27 12:53:30.497497 +00:00 | 2022-04-27 12:53:31.978762 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-migrationtemp-prime/watch-wD4lAH/s=db,c=100,w=60s,t=Sma, | market\_deal\_state | 2022-04-27 12:53:30.497497 +00:00 | 2022-04-27 12:53:31.825209 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-migrationtemp-prime/watch-wD4lAH/s=db,c=100,w=30s,t=Sin, | builtin | 2022-04-27 12:53:30.497358 +00:00 | 2022-04-27 12:53:30.497410 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-migrationtemp-prime/watch-wD4lAH/s=db,c=100,w=30s,t=Sin, | id\_address | 2022-04-27 12:53:30.497368 +00:00 | 2022-04-27 12:53:31.306852 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |

**lily-production-mainnet-analysis-migrationtemp-minerstate/watch-lfLS0R/s=db,c=100,w=60s,t=Smi,**
| height | reporter | task | started\_at | completed\_at | state\_root | status | status\_information | errors\_detected |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1758486 | lily-production-mainnet-analysis-migrationtemp-minerstate/watch-lfLS0R/s=db,c=100,w=60s,t=Smi, | miner\_fee\_debt | 2022-04-27 12:54:00.545092 +00:00 | 2022-04-27 12:54:01.521157 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-migrationtemp-minerstate/watch-lfLS0R/s=db,c=100,w=60s,t=Smi, | miner\_current\_deadline\_info | 2022-04-27 12:54:00.545092 +00:00 | 2022-04-27 12:54:01.526937 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-migrationtemp-minerstate/watch-lfLS0R/s=db,c=100,w=60s,t=Smi, | miner\_info | 2022-04-27 12:54:00.545092 +00:00 | 2022-04-27 12:54:01.526360 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-migrationtemp-minerstate/watch-lfLS0R/s=db,c=100,w=60s,t=Smi, | miner\_locked\_fund | 2022-04-27 12:54:00.545092 +00:00 | 2022-04-27 12:54:01.509620 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-migrationtemp-minerstate/watch-lfLS0R/s=db,c=100,w=60s,t=Smi, | builtin | 2022-04-27 12:54:00.545082 +00:00 | 2022-04-27 12:54:00.545138 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-migrationtemp-minerstate/watch-lfLS0R/s=db,c=100,w=60s,t=Smi, | miner\_pre\_commit\_info | 2022-04-27 12:54:00.545092 +00:00 | 2022-04-27 12:54:01.966984 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-migrationtemp-minerstate/watch-lfLS0R/s=db,c=100,w=60s,t=Smi, | miner\_sector\_deal | 2022-04-27 12:54:00.545092 +00:00 | 2022-04-27 12:54:19.749093 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-migrationtemp-minerstate/watch-lfLS0R/s=db,c=100,w=60s,t=Smi, | miner\_sector\_event | 2022-04-27 12:54:00.545092 +00:00 | 2022-04-27 12:54:19.750272 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-migrationtemp-minerstate/watch-lfLS0R/s=db,c=100,w=60s,t=Smi, | miner\_sector\_infos | 2022-04-27 12:54:00.545092 +00:00 | 2022-04-27 12:54:01.434936 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-migrationtemp-minerstate/watch-lfLS0R/s=db,c=100,w=60s,t=Smi, | miner\_sector\_infos\_v7 | 2022-04-27 12:54:00.545092 +00:00 | 2022-04-27 12:54:19.749132 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
| 1758486 | lily-production-mainnet-analysis-migrationtemp-minerstate/watch-lfLS0R/s=db,c=100,w=60s,t=Smi, | miner\_sector\_post | 2022-04-27 12:54:00.545092 +00:00 | 2022-04-27 12:54:10.276339 +00:00 | bafy2bzacedh52lpwlczgqjdbsuhvurpkyobpmphsfkokc73u6kr75wzhgi3ki | OK | NULL | NULL |
