### ISSUE TITLE
`lily job wait` respects Ctrl-C

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#961]
### Description

There is no way to interrupt `lily job wait`. It would be a nice convenience if this were included. Very low priority.

### Acceptance criteria

- [ ] Ctrl-C ends the `lily job wait` process

**Comment by frrist** [comment]
There's even a TODO for this, should be a fairly straight-forward change to make if you want to pick it up?
https://github.com/filecoin-project/lily/blob/master/lens/lily/impl.go#L459
