### ISSUE TITLE
`--tasks` does not parse comma-separated tasks

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#964]
### Describe the bug:

`lily job run --tasks="block_header,block_parent,drand_block_entrie,verified_registry_verified_client"`

`lily job run --tasks=block_header,block_parent,drand_block_entrie,verified_registry_verified_client`

In both cases, `tasks` are interpreted as a single string which fails to start (as that long string of `block_header,block_parent,drand_block_entrie,verified_registry_verified_client` is not a task name.

### Steps to Reproduce:

See above.

### Lily Version: vx.x.x

`v0.9.0+10-g4194bbe`

**Comment by frrist** [comment]
Possibly related to https://github.com/urfave/cli/issues/1143, investigating
